include::attributes.adoc[]
include::entities.adoc[]

= {productname} {productversion} Release Notes

ifeval::['{release_type}' != 'public']
[WARNING]
!!! This is a preview release. Not to be distributed outside of SUSE !!!
endif::[]

[WARNING]
This software is not ready for productive use.

[NOTE]
The released version is {productname} {productversion}

== Supported Platforms

This release supports deployment on

* {soc} 8
* VMWare ESXi {vmware_version}

== Changes To Base Os

=== Base Operating System Now Sle15 Sp1

The previous version used a minimal OS image called MicroOS. {productname} {productmajor} uses standard {sle} Server 15 SP1 as the base platform OS. CaaSP can be installed as an extension on top of that. Because SLES 15 is designed to address both cloud native and legacy workloads, these changes make it easier for customers who want to modernize their infrastructure by moving existing workloads to a {kube} framework.

Transactional-updates are available as a technical preview but {productname} {productmajor} will initially ship without the transactional-update mechanism enabled. The regular zypper workflow allows use of interruption free node reboot. The SLES update process should help customers integrate a Kubernetes platform into their existing operational infrastructure more easily, nevertheless transactional updates are still the preferred process for some customers, which is why we provide both options.

=== Software Now Shipped As Packages Instead Of Disk Image

In the previous version the deployment of the software was done by downloading and installing a disk
image with a pre-baked version of the product. In {productname} {productmajor} the software is distributed
 as RPM packages from an extension module in {sle} 15 SP1. This adaptation towards containers and {sles} mainly gives customers more deployment flexibility.

=== Components Even More Containerized

We moved more of the components into containers, namely all the control plane components:
`etcd`, `kube-apiserver`, `kube-controller-manager` and `kube-scheduler`.
The only pieces that are now running uncontainerized are `CRI-O`, `kubelet` and `kubeadm`.

=== New Deployment Methods

We are using a combination of `caaspctl` (custom wrapper around kubeadm) and HashiCorp Terraform to deploy SUSE CaaS Platform machines and clusters. We provide terraform state examples that you can modify to roll out clusters.

Note: You must roll out a load balancer manually, this is currently not possible by using terraform. Find an example of a possible load balancer configuration based on SUSE Linux Enterprise 15 SP1 and nginx in the Deployment guide:  https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_load_balancer

== Changes To Kubernetes Stack

=== Updated Kubernetes

{productname} {productversion} ships with Kubernetes {kube_version}.

=== CRI-O Replaces Docker

{productname} now uses CRI-O {crio_version} as the default container runtime.
CRI-O is a container runtime interface based on the OCI standard technology.
The choice of CRI-O allows us to pursue our open-source agenda better than competing technologies.

CRI-O's simplified architecture is tailored explicitly for {kube} and has a reduced footprint but also
guarantees full compatibility with existing customer images thanks to its adherence to OCI standards.
Other than Docker, CRI-O allows to update the container runtime without stopping workloads; providing improved flexibility and maintainabilitty to all {productname} users.

We will strive to maintain {productname}'s compatibility with Docker in the future.

=== Cilium Replaces Flannel

{productname} now uses Cilium {cilium_version} as the Container Networking Interface enabling networking policy support.

== Obsolete Components

=== Salt

Orchestration of the cluster no longer relies on Salt. Orchestration is instead achieved with `kubeadm` and `caaspctl`.

=== Admin Node / Velum

The Admin Node is no longer necessary. The cluster will now be controlled by the master nodes and through API with `caaspctl` on the local workstation. This also means the Velum dashboard is no longer available.

== Known Issues

=== Renaming `caaspctl`

The `caaspctl` tool will be renamed from it's working title to `caaspctl` with the release of {productname} Beta 3.

=== Other Known Issues:

* caaspctl option "control-plane" not marked as required in help output: https://bugzilla.suse.com/show_bug.cgi?id=1136368
* MemoryAccounting and CPUAccounting not enabled: https://bugzilla.suse.com/show_bug.cgi?id=1136363
* Insufficient memory causes nodes to be overloaded during conformance tests: https://bugzilla.suse.com/show_bug.cgi?id=1135916
** Use a 8gb/4vcpu configuration for all the machines as a work around
* After `node remove` and `node reset` a node cannot be rejoined due to masked kubelet.service: https://bugzilla.suse.com/show_bug.cgi?id=1136371
* AppArmor is disabled for pod deployments because of missing AppArmor profiles: https://bugzilla.suse.com/show_bug.cgi?id=1136403
* Wrong instructions for the user from kubeadm: https://bugzilla.suse.com/show_bug.cgi?id=1136404
* Cilium pod gets terminated and then fixes itself: https://bugzilla.suse.com/show_bug.cgi?id=1136406
* Cilium cannot run on kernel-default-base in JeOS: https://bugzilla.suse.com/show_bug.cgi?id=1134743
* Disk size for individual instances is not customizable by the user: https://bugzilla.suse.com/show_bug.cgi?id=1136045
* Reset commands  on wrong IP addresses successfully pass: https://bugzilla.suse.com/show_bug.cgi?id=113527
* User creation with terraform fails and renders cluster unusable: https://bugzilla.suse.com/show_bug.cgi?id=1136366
* The `caaspctl cluster init my-cluster` does not pass without the "control-plane" option: https://bugzilla.suse.com/show_bug.cgi?id=1136368
* caaspctl package contains terraform examples with internal configuration: https://bugzilla.suse.com/show_bug.cgi?id=1136218
* SUSE-CaaSP-Management pattern installs base system on fresh SLE-15-SP1 server: https://bugzilla.suse.com/show_bug.cgi?id=1136177
