include::attributes.adoc[]
include::entities.adoc[]

= {productname} {productversion} Release Notes

{productname} is an enterprise-ready {kube}-based container management solution.

== About the Release Notes

// for beta release:
// The most recent version of the Release Notes is available online at https://susedoc.github.io/caasp-release-notes/beta/release-notes/single-html/.

// for public release:
The most recent version of the Release Notes is available online at https://www.suse.com/releasenotes or https://documentation.suse.com/suse-caasp/4/.

Entries can be listed multiple times if they are important and belong to multiple sections.

Release notes usually only list changes that happened between two subsequent releases.
Certain important entries from the release notes documents of previous product versions may be repeated.
To make such entries easier to identify, they contain a note to that effect.

== Changes in 4.2.0

=== Deprecations in 4.2.0

- The hyperkube image, combining multiple kubernetes binaries, is planned for
  removal in 4.3.0, due to upstream deprecations.
  If running {productname} in an airgapped environment, please ensure that all
  our images are mirrored.

- Remove ability to re-enable serving deprecated APIs types: 
* `extensions/v1beta1`
* `apps/v1beta1`
* `apps/v1beta2`

For more information check: https://github.com/kubernetes/kubernetes/issues/43214

=== {kube} update

4.2.0 brings in a {kube} update, precisely to 1.17. The list of features and bug fixes is long, see:

See more at https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md

=== Addon customization persistence

This release adds `kustomize` to persist addon configuration changes across updates and reboots.


=== skuba: Disabling `firewalld`

skuba should disable `firewalld` when bootstrapping/joining a node. Adds a startup step to check that `firewalld` is disabled. This was previously done using `cloud-init` but this would not work on bare metal.

=== datastore for vmware

{vmware} {tf} config now supports setting a datastore cluster as the storage backend. Please refer to the  link:https://documentation.suse.com/suse-caasp/4.2/html/caasp-deployment/_deployment_instructions.html#_deploying_vms_from_the_template[Deployment Instructions] for more information.


=== Bugs Fixed in 4.2.0 since 4.1.2

* link:https://bugzilla.suse.com/show_bug.cgi?id=1161056[bsc#1161056] [cri-o] - Fix upgrade from 4.0.3 to 4.1.0 - skuba node upgrade - fails due to crio-wipe.service not starting
* link:https://bugzilla.suse.com/show_bug.cgi?id=1159108[bsc#1159108] [admin-guide] grafana helm chart version newer than upstream but older image version / grafana version!
* link:https://bugzilla.suse.com/show_bug.cgi?id=1157337[bsc#1157337] [skuba] After cluster creation all DEX and all GANGWAY pods run on the first master
* link:https://bugzilla.suse.com/show_bug.cgi?id=1152334[bsc#1152334] [skuba] skuba update management - HAS-UPDATES HAS-DISRUPTIVE-UPDATES -> no vs none
* link:https://bugzilla.suse.com/show_bug.cgi?id=1160460[bsc#1160460] [podman] Update podman to 1.8.0
* link:https://bugzilla.suse.com/show_bug.cgi?id=1164390[bsc#1164390] [conmon] Add conmon to SLE15 Containers Module
* link:https://bugzilla.suse.com/show_bug.cgi?id=1162093[bsc#1162093] [kubernetes] kubelet referenced wrong volume-plugin dir after upgrade
* link:https://bugzilla.suse.com/show_bug.cgi?id=1121353[bsc#1121353] [kubernetes] Kubernetes – Master node pod configured with Privileged PSP

[[docs-changes-420]]
=== Documentation Changes

* The QuickStart Guide has been removed pending review and rewrite.
Please use the link:{docurl}single-html/caasp-deployment/[Deployment Guide].
* link:{docurl}single-html/caasp-admin/#_disaster_recovery[Disaster Recovery] is now documented in the Admin Guide.
* A link:{docurl}single-html/caasp-deployment/deployment-system-requirements.html#_replicas[subchapter on Managing Replicas] has been added to Deployment Requirements.
* The link:{docurl}single-html/caasp-deployment/#airgap-container_registry-mirror[list of required addon images] was updated.
* {cap} integration was removed from the {productname} Admin Guide. Please now refer to: link:https://documentation.suse.com/suse-cap/{cap_version}/single-html/cap-guides/#cha-cap-depl-caasp[Deploying SUSE Cloud Application Platform on SUSE CaaS Platform].
* A note about using the `--non-interactive-include-reboot-patches` was added to the link:{docurl}/single-html/caasp-admin/#disabling-automatic-updates[Admin Guide].
* Instructions on how to update Dex have been enhanced. For details, see link:{docurl}single-html/caasp-admin/#_sec.admin.security.rbac.update[the Admin Guide].
* Updated the air gapped deployment with a new diagram. See the link:{docurl}single-html/caasp-deployment/#airgap-concepts[Admin Guide].
* Added example how to set up link:{docurl}single-html/caasp-admin/caasp-admin.html#recording_rules_configuration_example[Prometheur Recording Rules].
* Added link:{docurl}single-html/caasp-admin/caasp-admin.html#_aws_deployment_fails_with_cannot_attach_profile_error[instructions how to troubleshoot the `"cannot attach profile" error` from AWS].
* The link:{docurl}single-html/caasp-deployment/#_glossary[Glossary] was reintroduced to all our guides.
* Various other fixes and improvements (Refer to: https://github.com/SUSE/doc-caasp/releases).


=== Known issues

==== Updating packages without updating k8s

FILLIN


=== Required Actions

==== Kubernetes 1.17

In order to update to {kube} 1.17, follow the instructions in the link:https://documentation.suse.com/suse-caasp/4.2/html/caasp-admin/_cluster_updates.html#_updating_kubernetes_components[admin guide].

MENTION known bug


==== `conmon` and {crio}

Conmon and [crio} will be updated by `skuba-update`. No action is required from your side. For more info see https://documentation.suse.com/suse-caasp/4.2/html/caasp-admin/_cluster_updates.html#_base_os_updates


==== skuba

In order to update skuba, you need to update the admin workstation. See detailed instructions at https://documentation.suse.com/suse-caasp/4.1/html/caasp-admin/_cluster_updates.html#_update_management_workstation


==== Generate the `kustomize` style addon configurations

You must convert your addon manifests to the new `kustomize` aware file structure and formats.
To do so please run the following command from your management workstation.

Replace `MASTER-NODE-IP` with an IP address/FQDN of one of your master nodes.
Replace `CLUSTER-DEFINITION-PATH` with the path to your existing cluster defintion files that were generated during the intial bootstrap/deployment.

----
skuba cluster init --control-plane MASTER-NODE-IP /tmp/new-cluster-init
mv CLUSTER-DEFINITION-PATH/addons CLUSTER-DEFINITION-PATH/addons-old
cp -r /tmp/new-cluster-init/addons CLUSTER-DEFINITION-PATH/
----

This will generate the existing addon configurations in the new format so you can amend them.

== Changes in 4.1.2

=== Deployment on AWS as Technology Preview

Deployment of {productname} on Amazon Web Services (AWS) has been tested and documented.
{tf} is used to deploy the infrastructure and the `skuba` tool to bootstrap the {kube} cluster on top of it.
For detailed instructions please see link:https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-deployment/#_deployment_on_amazon_aws[the Deployment Guide].
Please note that {productname} deployment on AWS may not be functionally complete, and is not intended for production use.

=== Terraform Upgrade

{productname} can now be deployed with *{tf} 0.12*. All details of the new version
can be found in the link:https://www.hashicorp.com/blog/terraform-0-1-2-preview/[HashiCorp Documentation].
The official website for the {tf} 0.12 upgrade is https://www.terraform.io/upgrade-guides/0-12.html.

=== etcd Backup and Restore for Master Nodes Disaster Recovery

* Provide etcd backup process on-demand or on a schedule to prevent etcd data corruption.
* Provide etcd restore process to recover failed master node(s) to restore etcd quorum for cluster serving.

For detailed instructions please see link: https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#_backup_etcd_cluster_data[the Administration Guide].

=== Velero for Disaster Recovery

* Provide Velero as a solution for data protection and data migration by backing up and migrating Kubernetes resources and persistent volumes to and from externally supported storage backend on demand or on a schedule.

For detailed instructions please see link: https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#_disaster_recovery[the Administration Guide].

=== Required Actions

==== Upgrade {tf} Files and State

In order to seamlessly switch to {tf} 0.12 you need to make sure that:

* All files follow the new syntax for the link:https://github.com/hashicorp/hcl[HashiCorp Configuration Language] included in {tf} 0.12
* All boolean values are `true` or `false` and *not* 0 or 1
* All variables are explicitly declared
* All dependencies are explicitly declared to reach the expected behavior

==== Recommended Procedure

Enter your {tf} files/state folder and:

* Install the latest version of {tf} using `zypper in terraform` (the installed version should be 0.12.19)
* Navigate to your {tf} root folder (e.g. `/usr/share/caasp/terraform/vmware`)
* Migrate {tf} files with the automatic migration tool by running `terraform 0.12upgrade`
** For OpenStack, run the <<terraform-openstack-extra-ops>> (see below)
** Run `terraform apply` to update the {tf} definitions to the new format used by 0.12
+
[IMPORTANT]
====
If you do not update the definitions before running {tf} again your output might contain `nil`/`null` strings when you run `terraform refresh` followed by `terraform output`.
This can break automations that are based on the output. Please make sure you have updated/applied all definitions before running {tf}.
====
* Run `zypper up skuba`
* You can then run the `terraform init/plan/apply` commands as usual.

[[terraform-openstack-extra-ops]]
==== Extra Operations for In-place Upgrade of OpenStack {tf} Files

* Replace any boolean values written as a number with `false`/`true`.
  For example, for the variables in `openstack/variables.tf`
  (and their equivalent in your `terraform.tfvars` file), replace
  `default = 0` with `default = false` in the variables
  `workers_vol_enabled` and `dnsentry`. Do the same for
  any extra boolean variable you might have added.
* Introduce a `depends_on` on the resource `"openstack_compute_floatingip_associate_v2" "master_ext_ip"` in `master-instance.tf`:
+
----
depends_on = [openstack_compute_instance_v2.master]
----
+
* Introduce a `depends_on` on the resource `"master_wait_cloudinit"` in `master-instance.tf`:
+
----
depends_on = [
  openstack_compute_instance_v2.master,
  openstack_compute_floatingip_associate_v2.master_ext_ip
]
----
+
* Introduce a `depends_on` on the resources
  `"openstack_compute_floatingip_associate_v2" "worker_ext_ip"` and
  `"null_resource" "worker_wait_cloudinit"` in `worker-instance.tf`, similarly to the ones for master.
  Replace `master` with `worker` in the examples above.
* Update the resources `resource "openstack_compute_instance_v2" "master"`
  and `resource "openstack_compute_instance_v2" "worker"` with
  `master-instance.tf` and `worker-instance.tf` respectively. Add the following resources:
+
----
lifecycle {
  ignore_changes = [user_data]
}
----
+
[NOTE]
====
The above option is needed because {tf} will detect all machines as new resources when `user_data` changes during the upgrade.
====
+
This will make it possible to update your cluster from a {tf} 0.11 state
into a {tf} 0.12 state without tearing it down completely.

[WARNING]
=========
When adding `lifecycle { ignore_change = [user_data] }` in your master and
worker instances, you will effectively prevent updates of nodes, should you or
SUSE update the `user_data`. This should be removed as soon as possible after the
migration to {tf} 0.12.
=========

==== etcdctl
Run `zypper in etcdctl` in the management host to install etcdctl.

==== Update packages for general fixes
Update `skuba` package and `patterns-caasp-Management` on your management workstation as you would do with any other package.

Refer to: link:https://documentation.suse.com/sles/15-SP1/single-html/SLES-admin/#sec-zypper-softup-update[https://documentation.suse.com/sles/15-SP1/single-html/SLES-admin/#sec-zypper-softup-update]

Updating `patterns-caasp-Management` will install the new terraform providers for AWS.

Packages on your cluster nodes (cri-o) will be updated automatically by `skuba-update` link:https://documentation.suse.com/suse-caasp/4.1/html/caasp-admin/_cluster_updates.html#_base_os_updates


=== Bugs Fixed in 4.1.2 since 4.1.1

* link:https://bugzilla.suse.com/show_bug.cgi?id=1161056[bsc#1161056] [cri-o] - Fix upgrade from 4.0.3 to 4.1.0 - skuba node upgrade - fails due to crio-wipe.service not starting
* link:https://bugzilla.suse.com/show_bug.cgi?id=1161179[bsc#1161179] [cri-o] - Fix invalid apparmor profile
* link:https://bugzilla.suse.com/show_bug.cgi?id=1158440[bsc#1158440] [terraform] - Update in SLE-15 (bsc#1158440, CVE-2019-19316)
* link:https://bugzilla.suse.com/show_bug.cgi?id=1148092[bsc#1148092] [terraform] - Include in SLE-15 (bsc#1148092, jsc#ECO-134)
* link:https://bugzilla.suse.com/show_bug.cgi?id=1145003[bsc#1145003] [terraform-provider-openstack] - Update to version 1.19.0
* link:https://bugzilla.suse.com/show_bug.cgi?id=1159082[bsc#1159082] [grafana] - Fix some missing container images of grafana helm chart
* link:https://bugzilla.suse.com/show_bug.cgi?id=1161225[bsc#1161225] [grafana] - Fix grafana helm chart has app version 6.4.2 but version is 6.2.5
* link:https://bugzilla.suse.com/show_bug.cgi?id=1161110[bsc#1161110] [grafana] - Fix Grafana dashboard should not name "CaaSP" but "SUSE (r) CaaS Platform"
* link:https://bugzilla.suse.com/show_bug.cgi?id=1162093[bsc#1162093] [kubelet] - Release fix for volume-plugin-dir in kubernetes packages
* link:https://bugzilla.suse.com/show_bug.cgi?id=1160463[bsc#1160463] [skuba] - Fix skuba-update --version always 0.0.0
* link:https://bugzilla.suse.com/show_bug.cgi?id=1157323[bsc#1157323] [skuba] - Fix need a way to report on current available CaaSP version vs. installed version

[[docs-changes-412]]
=== Documentation Changes

* Added link:{docurl}single-html/caasp-deployment/#_deployment_on_amazon_aws[AWS deployment instructions] (Tech Preview)
* Added link:{docurl}single-html/caasp-deployment/#deployment_bare_metal[KVM deployment instructions]
* Improved instructions for Monitoring to link:{docurl}single-html/caasp-admin/#_monitoring_stack[deploy Grafana in a sub path] and enhanced ingress settings
* Fix unspecific expression in link:{docurl}single-html/caasp-admin/#alertmanager_configuration_example[AlertManager example]
* Added notes on link:single-html/caasp-admin/#_control_plane_nodes_certificates_rotation[certificate rotation for the control plane]
* Various other fixes and improvements (Refer to: https://github.com/SUSE/doc-caasp/releases)

== Changes in 4.1.1

* skuba fixes (see below)
* supportutils-plugin-suse-caasp fixes (see below)
* kubernetes and cri-o fixes (see below)
* caasp-release-notes fixes (see below)
* prometheus fixes (see below)
* {crio} now uses the system proxy settings (see <<docs-changes-411>>)

=== Required Actions

==== Update packages for general fixes and added supportconfig plugin
Update skuba and kubernetes-client packages on your management workstation as you would do with any other package.

Refer to: link:https://documentation.suse.com/sles/15-SP1/single-html/SLES-admin/#sec-zypper-softup-update[https://documentation.suse.com/sles/15-SP1/single-html/SLES-admin/#sec-zypper-softup-update]

Packages on your cluster nodes (cri-o, kubernetes, supportutils-plugin-suse-caasp) will be updated automatically by `skuba-update` link:https://documentation.suse.com/suse-caasp/4.1/html/caasp-admin/_cluster_updates.html#_base_os_updates

==== Fix Prometheus `kube-state-metrics`
Use `helm upgrade` command to fix the Prometheus `kube-state-metrics` image.

Finally, in order to use new Prometheus `pushgateway` image, enable the service in your `prometheus-config-values.yaml` config file:

----
pushgateway:
  enabled: true
----

Then run the `helm upgrade` command link:https://helm.sh/docs/intro/using_helm/#helm-upgrade-and-helm-rollback-upgrading-a-release-and-recovering-on-failure[].

Afterwards you can deploy Prometheus as usual. Refer to: link:https://documentation.suse.com/suse-caasp/4.1/html/caasp-admin/_monitoring.html#_prometheus[].

=== Bugs Fixed in 4.1.1 since 4.1.0

* link:https://bugzilla.suse.com/show_bug.cgi?id=1161179[bsc#1161179] [cri-o] - cilium crashes with "apparmor failed to apply profile: write /proc/self/attr/exec: no such file or directory
* link:https://bugzilla.suse.com/show_bug.cgi?id=1161056[bsc#1161056] [cri-o] - upgrade from 4.0.3 to 4.1.0 - skuba node upgrade - fails due to crio-wipe.service not starting
* link:https://bugzilla.suse.com/show_bug.cgi?id=1155323[bsc#1155323] [cri-o] - Include system proxy settings in service if present
* link:https://bugzilla.suse.com/show_bug.cgi?id=1159452[bsc#1159452] [skuba] - Fixed do not panic when version is unknown
* link:https://bugzilla.suse.com/show_bug.cgi?id=1157802[bsc#1157802] [skuba] - Enhanced skuba auth login help/error message
* link:https://bugzilla.suse.com/show_bug.cgi?id=1155810[bsc#1155810] [skuba] - Refactored to fix CaaSP SSL / PKI / CA Infrastructure unclear and probably inconsistent and wrong?
* link:https://bugzilla.suse.com/show_bug.cgi?id=1157802[bsc#1157802] [skuba] - skuba auth login help should mention the port that needs to be use (:32000)
* link:https://bugzilla.suse.com/show_bug.cgi?id=1137337[bsc#1137337] [skuba] - Skuba log level description is missing
* link:https://bugzilla.suse.com/show_bug.cgi?id=1155593[bsc#1155593] [kubernetes] - second master join always fails
* link:https://bugzilla.suse.com/show_bug.cgi?id=1160443[bsc#1160443] [supportutils-plugin-suse-caasp] - Extend supportconfig to check certificates expiration time
* link:https://bugzilla.suse.com/show_bug.cgi?id=1152335[bsc#1152335] [supportutils-plugin-suse-caasp] - Add etcd logs for v4
* link:https://bugzilla.suse.com/show_bug.cgi?id=1160600[bsc#1160600] [caasp-release-notes] - caasp-release package points to caasp-release-notes 4.0
* link:https://bugzilla.suse.com/show_bug.cgi?id=1159074[bsc#1159074] [prometheus] - Prometheus pushgateway image v0.8.0 missing on registry.suse.com/caasp/v4
* link:https://bugzilla.suse.com/show_bug.cgi?id=1161975[bsc#1161975] [prometheus] - kube-state-metrics - endless "Failed to list *v1beta1.ReplicaSet: the server could not find the requested resource" on 1.16.2

[[docs-changes-411]]
=== Documentation Changes

* Added instructions for link:{docurl}single-html/caasp-admin/#_stratos_web_console[Stratos Web Console (Tech Preview)]
* Added instructions for link:{docurl}single-html/caasp-deployment/#_storage_performance[etcd storage performance testing]
* Added instructions for link:{docurl}single-html/caasp-admin/#troubleshooting-etcd[`etcd` troubleshooting]
* Updated link:{docurl}single-html/caasp-admin/#_configuring_httphttps_proxy_for_cri_o[{crio} proxy configuration instructions]
* Updated upgrade instructions with more link:{docurl}/single-html/caasp-admin/#disabling_automatic_updates[information about manual upgrades and reboots]
* Various minor fixes and improvements (Refer to: https://github.com/SUSE/doc-caasp/releases)


== Changes in 4.1.0

=== {kube} update

{productname} now ships with {kube} {kube_version}.
Most of the significant changes relate to this upgrade, as more than 31 enhancements were merged in the {kube} {kube_version} release.
You can read a short summary of the changes under <<kubernetes_updates>>.
Manual actions are required for 4.1.0 release.

=== Helm security update

Moreover, helm has been updated to fix a security issue (link:https://www.suse.com/security/cve/CVE-2019-18658/[CVE-2019-18658]).

=== Stratos, a web console for {kube}

Stratos is now available as tech preview for {productname}. Stratos is a
web console for {kube} and for Cloud Foundry.
A single instance of Stratos can be used to monitor and interact with different
{kube} clusters as long as their API endpoints are reachable by Stratos.

Stratos integrates with Prometheus: it can scrape metrics collected
by Prometheus and show them using pre-built charts.

Finally Stratos can be used to interact with helm chart repositories. It can
show the charts available and install them straight from its web interface.
It can also show all the workloads that are running on a {kube} that have
been created by helm chart.

[NOTE]
====
The helm chart integration is a tech preview feature of Stratos
that must be enabled at deployment time.
====

=== Required Actions

==== Skuba and helm update Instructions

Update skuba and helm on your management workstation as you would do with any other package.

Refer to: link:https://documentation.suse.com/sles/15-SP1/single-html/SLES-admin/#sec-zypper-softup-update[https://documentation.suse.com/sles/15-SP1/single-html/SLES-admin/#sec-zypper-softup-update]

[WARNING]
====
When running helm-init you may hit a link:https://bugzilla.suse.com/show_bug.cgi?id=1159047[known bug on the certificate validation]:

----
https://kubernetes-charts.storage.googleapis.com is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: x509: certificate signed by unknown authority
----

In order to fix this, run:

----
sudo update-ca-certificates
----

====


After updating helm to latest version on the management host, you have to also upgrade the helm-tiller image in the cluster, by running:

----
helm init \
    --tiller-image registry.suse.com/caasp/v4/helm-tiller:2.16.1 \
    --service-account tiller --upgrade
----

==== Upgrade Your {kube} Cluster

Use skuba to upgrade your {kube} cluster as link:https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#handling_updates[documented in the Administration guide].

[WARNING]
====
Please, do not run `zypper patch` manually on your nodes.
If you do, you will see an error about a conflict when patching {crio}.
This is expected, because the patch is not supposed to be installed this way.

Instead, cluster updates are being handled by skuba as link:{docurl}/single-html/caasp-admin/#handling_updates[documented in the Administration guide].
====

==== Update Your {kube} Manifests for {kube} {kube_version}:

Some API resources are moved to stable, while others have been
moved to different groups or deprecated.

The following will impact your deployment manifests:

*  `DaemonSet`, `Deployment`, `StatefulSet`, and `ReplicaSet` in
  `extensions/` (both `v1beta1` and `v1beta2`) is deprecated.
  Migrate to `apps/v1` group instead for all those objects.
  Please note that `kubectl convert` can help you migrate all the
  necessary fields.
*  `PodSecurityPolicy` in `extensions/v1beta1` is deprecated. Migrate to
  `policy/v1beta1` group for `PodSecurityPolicy`.
  Please note that `kubectl convert` can help you migrate all the
  necessary fields.
*  `NetworkPolicy` in `extensions/v1beta1` is deprecated. Migrate to
  `networking.k8s.io/v1` group for `NetworkPolicy`.
  Please note that `kubectl convert` can help you migrate all the
  necessary fields.
*  `Ingress` in `extensions/v1beta1` is being phased out. Migrate to
  `networking.k8s.io/v1beta1` as soon as possible.
  This new API does not need to update other API fields and therefore
  only a path change is necessary.
*  Custom resource definitions have moved from `apiextensions.k8s.io/v1beta1`
  to `apiextensions.k8s.io/v1`.

Please also see https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ for more details.

=== Bugs Fixed in 4.1.0 since 4.0.3

* link:https://bugzilla.suse.com/show_bug.cgi?id=1144065[bsc#1144065] [cri-o] - (link:https://www.suse.com/security/cve/CVE-2019-10214[CVE-2019-10214]) VUL-0: CVE-2019-10214: libcontainers-common: library does not enforce TLS connections
* link:https://bugzilla.suse.com/show_bug.cgi?id=1118898[bsc#1118898] [cri-o] - (link:https://www.suse.com/security/cve/CVE-2018-16874[CVE-2018-16874]) VUL-0: CVE-2018-16874: go: cmd/go: directory traversal
* link:https://bugzilla.suse.com/show_bug.cgi?id=1100838[bsc#1100838] [cri-o] - cri-o does not block /proc/acpi pathnames (i.e., also affected by (link:https://www.suse.com/security/cve/CVE-2018-10892[CVE-2018-10892]))
* link:https://bugzilla.suse.com/show_bug.cgi?id=1118897[bsc#1118897] [etcd] - (link:https://www.suse.com/security/cve/CVE-2018-16873[CVE-2018-16873]) VUL-0: CVE-2018-16873: go: cmd/go: remote command execution
* link:https://bugzilla.suse.com/show_bug.cgi?id=1118899[bsc#1118899] [etcd] - (link:https://www.suse.com/security/cve/CVE-2018-16875[CVE-2018-16875]) VUL-0: CVE-2018-16875: go: crypto/x509: CPU denial of service
* link:https://bugzilla.suse.com/show_bug.cgi?id=1156646[bsc#1156646] [helm] - (link:https://www.suse.com/security/cve/CVE-2019-18658[CVE-2019-18658]) VUL-0: CVE-2019-18658: helm: commands that deal with loading a chart as a directory or packaging a chart provide an opportunity for a maliciously designed chart to include sensitive content such as /etc/passwd
* link:https://bugzilla.suse.com/show_bug.cgi?id=1152861[bsc#1152861] [kubernetes] - (link:https://www.suse.com/security/cve/CVE-2019-11253[CVE-2019-11253]) VUL-0: CVE-2019-11253: kubernetes: YAML parsing vulnerable to "Billion Laughs" attack, allowing for remote denial of service
* link:https://bugzilla.suse.com/show_bug.cgi?id=1146991[bsc#1146991] [kubernetes] - BPF filesystem is not mounted, possible downtime when cilium pods are restarted
* link:https://bugzilla.suse.com/show_bug.cgi?id=1147142[bsc#1147142] [kubernetes] - Update golang/x/net dependency to bring in fixes for (link:https://www.suse.com/security/cve/CVE-2019-9512[CVE-2019-9512]), (link:https://www.suse.com/security/cve/CVE-2019-9514[CVE-2019-9514])
* link:https://bugzilla.suse.com/show_bug.cgi?id=1143813[bsc#1143813] [kubernetes] - kubelet sometimes starting too fast
* link:https://bugzilla.suse.com/show_bug.cgi?id=1143813[bsc#1143813] [skuba] - CaaSP SSL / PKI / CA Infrastructure unclear and probably inconsistent and wrong?
* link:https://bugzilla.suse.com/show_bug.cgi?id=1152335[bsc#1152335] [supportutils-plugin-suse-caasp] - supportconfig adjustments for CaaSP v4 missing

=== Documentation Updates

* Switched examples to use SUSE supported helm, Prometheus, nginx-ingress and Grafana charts and images
* link:{docurl}caasp-admin/single-html/_security.html#_deployment_with_a_custom_ca_certificate[Added instructions on how to replace {kube} certificates with custom CA certificate]
* link:{docurl}caasp-admin/single-html/_security.html#_replace_server_certificate_signed_by_a_trusted_ca_certificate[Added instructions to configure custom certificates for gangway and dex]
* link:{docurl}caasp-admin/single-html/_software_management.html#_installing_tiller[Added instructions for secured Tiller deployment]
* link:{docurl}caasp-deployment/single-html/#machine-id[Added notes about unique `machine-id` requirement]
* link:{docurl}caasp-deployment/single-html/#_autoyast_preparation[Added timezone configuration example for {ay}]
* link:https://github.com/SUSE/doc-caasp/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc[Various minor bugfixes and improvements]

=== Known issue: skuba upgrade could not parse "Unknown" as version ====

Running "skuba node upgrade plan" might fail with the error "could not parse "Unknown" as version" when a worker, after running "skuba node upgrade apply", had not fully started yet.

If you are running into this issue, please add some delay after running "skuba node upgrade apply" and prior to running "skuba node upgrade plan".

This is tracked in link:https://bugzilla.suse.com/show_bug.cgi?id=1159452[bsc#1159452]


== Changes in 4.0.3

* Prometheus and Grafana: official monitoring solution for {productname}
* Airgap: format change of https://documentation.suse.com/external-tree/en-us/suse-caasp/4/skuba-cluster-images.txt
* 389-ds fixes (see below)
* skuba fixes (see below)

=== Prometheus and Grafana: official monitoring solution for {productname}
Prometheus and Grafana were already link:https://documentation.suse.com/suse-caasp/4.0/html/caasp-admin/_monitoring.html#_monitoring_stack[documented] but based on upstream helm charts and containers.

In version {productversion}, official SUSE helm carts and containers are now available in the helm chart repository (`+kubernetes-charts.suse.com+`) and the container registry (`+registry.suse.com+`).

=== Airgap: Format Change

The format of https://documentation.suse.com/external-tree/en-us/suse-caasp/4/skuba-cluster-images.txt was changed to be able to express more data.
Specifically to add skuba and {productname} versions, so that one can match the images that should be pulled with the respective version.

This way, you can run air gapped production and staging clusters with different {productname} versions.

=== Required Actions

==== Skuba Update Instructions

Update skuba on your management workstation as you would do with any other package.

Refer to: link:https://documentation.suse.com/sles/15-SP1/single-html/SLES-admin/#sec-zypper-softup[{sls} 15 SP1 Admin Guide: Updating Software with Zypper]

==== Prometheus and Grafana Installation Instructions

You will need to use `helm` and `kubectl` to deploy Prometheus and Grafana.
Refer to: link:https://documentation.suse.com/suse-caasp/4.0/html/caasp-admin/_monitoring.html#_monitoring_stack[Monitoring chapter in the {productname} admin guide]

==== 389-ds Update Instructions

`389-ds` containers have been updated in `+registry.suse.com+` (see Bugs fixed below).
In order to deploy your `389-ds` container, see link:https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_configuring_an_external_ldap_server[Configuring and external ldap server at the {productname} admin guide]

=== Documentation Changes

* link:https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-admin/#_monitoring_stack[Updated monitoring documentation in the admin guide to reflect official charts/containers for monitoring stack]
* link:https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-admin#_deploying_an_external_389_directory_server[Added/Updated information about `389-ds` deployment and configuration]
* link:https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-deployment/#_networking[Added information about subnet sizing to deployment guide system requirements]
* link:https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-admin/#_deployment_with_a_custom_ca_certificate[Added information on using a cluster wide root CA to admin guide]
* link:https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-deployment/#_management_workstation[Add note about NTP client requirement for management workstation]
* link:https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-deployment/#_configuring_the_load_balancer[Added less aggressive nginx timeout values to examples]
* Unified use of placeholders in code examples to `<PLACEHOLDER>` format
* Various minor formatting and wording fixes

=== Bugs Fixed in 4.0.3 since 4.0.2

* link:https://bugzilla.suse.com/show_bug.cgi?id=1156667[bsc#1156667] [Prometheus and Grafana] - User "system:serviceaccount:monitoring:prometheus-kube-state-metrics" cannot list resource
* link:https://bugzilla.suse.com/show_bug.cgi?id=1140533[bsc#1140533] [Prometheus and Grafana] -  Prometheus and grafana images and helm charts on registry.suse.com
* link:https://bugzilla.suse.com/show_bug.cgi?id=1155173[bsc#1155173] [skuba] - skuba node upgrade does not really upgrade node successfully
* link:https://bugzilla.suse.com/show_bug.cgi?id=1151689[bsc#1151689] [skuba] -  Default verbosity hides most errors
* link:https://bugzilla.suse.com/show_bug.cgi?id=1151340[bsc#1151340] [389-ds] - ERR - add_new_slapd_process - Unable to start slapd because it is already running as process 8
* link:https://bugzilla.suse.com/show_bug.cgi?id=1151343[bsc#1151343] [389-ds] - The config /etc/dirsrv/slapd-*/dse.ldif can not be accessed. Attempting restore
* link:https://bugzilla.suse.com/show_bug.cgi?id=1151414[bsc#1151414] [389-ds] - NOTICE - dblayer_start - Detected Disorderly Shutdown last time Directory Server was running, recovering database.
* link:https://bugzilla.suse.com/show_bug.cgi?id=1157332[bsc#1157332] [patterns-caasp] - caasp-release rpm not installed - probably should be included in the patterns?

== Changes in 4.0.2

[NOTE]
====
Core addons are addons deployed automatically by `skuba` when you bootstrap a cluster. Namely:

* Cilium
* Dex
* Gangway
* Kured
* Default Pod Security Policies (PSP's)
====

* `skuba addon` command has been introduced to handle core addons
** `skuba addon upgrade plan` will inform about what core addons will be upgraded
** `skuba addon upgrade apply` will upgrade core addons in the current cluster

[[required-actions-402]]
=== Required Actions

* When using `skuba addon upgrade apply`, all settings of all addons will be reverted to the defaults. Make sure to reapply your changes after running `skuba addon upgrade apply`, had you modified the default settings of core addons.

=== Bugs fixed in 4.0.2 since 4.0.1

* link:https://bugzilla.suse.com/show_bug.cgi?id=1145568[bsc#1145568] [remove-node] failed disarming kubelet due to 63 character limitation
* link:https://bugzilla.suse.com/show_bug.cgi?id=1145907[bsc#1145907] LB dies when removing a master node in VMWare
* link:https://bugzilla.suse.com/show_bug.cgi?id=1146774[bsc#1146774] AWS: pod to service connectivity broken in certain cases
* link:https://bugzilla.suse.com/show_bug.cgi?id=1148090[bsc#1148090] Multinode cluster upgrade fails on 2nd master due to TLS handshake timeout
* link:https://bugzilla.suse.com/show_bug.cgi?id=1148412[bsc#1148412] Gangway uses CSS stylesheet from cloudflare.com
* link:https://bugzilla.suse.com/show_bug.cgi?id=1148524[bsc#1148524] Allow easy recovery from bootstrap failed during add-ons deployment phase
* link:https://bugzilla.suse.com/show_bug.cgi?id=1148700[bsc#1148700] worker node upgrade needs to use kubeletVersion in nodeVersionInfoUpdate type
* link:https://bugzilla.suse.com/show_bug.cgi?id=1149637[bsc#1149637] Misspelling of bootstrapping in a common error message
* link:https://bugzilla.suse.com/show_bug.cgi?id=1153913[bsc#1153913] Can not bootstrap an new cluster if a valid `kubectl` config is present
* link:https://bugzilla.suse.com/show_bug.cgi?id=1153928[bsc#1153928] Reboot can be triggered before skuba-update finishes
* link:https://bugzilla.suse.com/show_bug.cgi?id=1154085[bsc#1154085] skuba node upgrade shows component downgrade
* link:https://bugzilla.suse.com/show_bug.cgi?id=1154754[bsc#1154754] oauth2: cannot fetch token after 24 hours

== Changes in 4.0.1

* Updated Gangway container image (see <<required-actions-401>>)
* Added link:https://documentation.suse.com/suse-caasp/4/single-html/caasp-deployment/#_airgapped_deployment[air gap deployment instructions]
* Various bug fixes and improvements

[[required-actions-401]]
=== Required Actions

[[gangway-update]]
==== Update the Gangway Image

The gangway image that shipped with {productname} 4.0 must be updated manually by performing the following step:

====
kubectl set image deployment/oidc-gangway oidc-gangway=registry.suse.com/caasp/v4/gangway:3.1.0-rev4 --namespace kube-system
====

== Known Issues

You must update the gangway container image manually after update (see <<required-actions-401>> ).

For a full list of Known Issues refer to: link:{bugzilla_url}[Bugzilla].

== Supported Platforms

This release supports deployment on:

* {soc} 8
* VMWare ESXi {vmware_version}
* KVM
* Bare metal
+
({productname} {productversion} supports hardware that is certified for {slsa}
through the YES certification program. You will find a database of certified
hardware at https://www.suse.com/yessearch/.)

== What Is New

=== Base Operating System Is Now {slsa} 15 SP1

The previous version used a minimal OS image called MicroOS. {productname}
{productmajor} uses standard {slsa} 15 SP1 as the base platform OS.
{productname} can be installed as an extension on top of that. Because {slsa} 15 is
designed to address both cloud-native and legacy workloads,
these changes make it easier for customers who want to modernize their
infrastructure by moving existing workloads to a {kube} framework.

Transactional updates are available in {slsa} 15 SP1 as a technical preview but {productname}
{productmajor} will initially ship without the transactional-update mechanism enabled.
The regular zypper workflow allows use of interruption-free node reboot.
The {slsa} update process should help customers integrate a {kube} platform
into their existing operational infrastructure more easily, nevertheless transactional
updates are still the preferred process for some customers,
which is why we provide both options.

=== Software Now Shipped as Packages Instead of Disk Image

In the previous version, the deployment of the software was done by downloading and installing a disk
image with a pre-baked version of the product. In {productname} {productmajor}, the software is distributed
as RPM packages from an extension module in {slsa} 15 SP1.
This adaptation towards containers and {sls} mainly gives customers more deployment flexibility.

=== More Containerized Components

We moved more of the components into containers, namely all the control plane components:
`etcd`, `kube-apiserver`, `kube-controller-manager`, and `kube-scheduler`.
The only pieces that are now running uncontainerized are `CRI-O`, `kubelet` and `kubeadm`.

=== New Deployment Methods

We are using a combination of `skuba` (custom wrapper around kubeadm) and
HashiCorp Terraform to deploy {productname} machines and clusters.
We provide Terraform state examples that you can modify to roll out clusters.

Deployment on bare metal using AutoYaST has now also been tested and documented:
link:https://documentation.suse.com/suse-caasp/4/single-html/caasp-deployment/#deployment_bare_metal[]

[NOTE]
You must deploy a load balancer manually.
This is currently not possible using Terraform.
Find example load balancer configurations
based on {sle} 15 SP1 and Nginx or HAProxy in the __{productname} Deployment Guide__:
https://documentation.suse.com/suse-caasp/4/single-html/caasp-deployment/#_load_balancer[]

=== Updates Using Kured

Updates are implemented with `skuba-update`, that makes use of the `kured`
tool and the SLE package manager. This is implemented in the skuba-update
tool which glues zypper and the kured tool (https://github.com/weaveworks/kured).
Kured (KUbernetes REboot Daemon) is a {kube} daemonset that performs safe
automatic node reboots when the need to do so is indicated by the package
management system of the underlying OS. Automatic updates can be manually
disabled and configured: https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#_cluster_updates

=== Automatic Installation of Packages For Storage Backends Discontinued

In previous versions {productname} would ship with packages to support all available storage backends.
This negated the minimal install size approach and is discontinued. If you require a specific software
package for your storage backend please install it using {ay}, {tf} or `zypper`.
Refer to: https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#_software_management


[[kubernetes_updates]]
=== Changes to the {kube} Stack

==== Updated Kubernetes

{productname} {productversion} ships with {kube} {kube_version}.

{kube} version 1.16 contains the following notable changes:

* Custom Resources Definitions (CRD) are out of the beta version and are
  generally available in the `apiextensions.k8s.io/v1` group.
* IPv4/IPv6 dual stack is officially in alpha.
Read up about the details of the new features of {kube} 1.16 here:
https://kubernetes.io/blog/2019/09/18/kubernetes-1-16-release-announcement/.

{kube} version 1.15 mainly contains enhancements to core {kube} APIs:

* CustomResourceDefinitions Pruning, -Defaulting and -OpenAPI Publishing.
* cluster life cycle stability and usability has been enhanced
  (`kubeadm init` and `kubeadm join` can now be used to configure and deploy an HA control plane)
* new functionality of the Container Storage Interface (volume cloning) is available.
Read up about the details of the new features of {kube} 1.15 here:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#115-whats-new

==== CRI-O Replaces Docker

{productname} now uses CRI-O {crio_version} as the default container runtime.
CRI-O is a container runtime interface based on the OCI standard technology.
The choice of CRI-O allows us to pursue our open-source agenda better than competing technologies.

CRI-O's simplified architecture is tailored explicitly for {kube} and has a reduced footprint but also
guarantees full compatibility with existing customer images thanks to its adherence to OCI standards.
Other than Docker, CRI-O allows to update the container runtime without stopping workloads;
providing improved flexibility and maintainabilitty to all {productname} users.

We will strive to maintain {productname}'s compatibility with the Docker Engine in the future.

==== Cilium Replaces Flannel

{productname} now uses Cilium {cilium_version} as the Container Networking
Interface enabling networking policy support.

=== Centralized Logging

The deployment of a Centralized Logging node is now supported for the purpose of
aggregating logs from all the nodes in the {kube} cluster.
Centralized Logging forwards system and {kube} cluster logs to a
specified external logging service, specifically the Rsyslog server,
using {kube} Metadata Module - `mmkubernetes`.


=== Obsolete Components

==== Salt

Orchestration of the cluster no longer relies on Salt.
Orchestration is instead achieved with `kubeadm` and `skuba`.

==== Admin Node / Velum

The admin node is no longer necessary. The cluster will now be controlled
by the master nodes and through API with `skuba` on any {sle} system, such as a local workstation.
This also means the Velum dashboard is no longer available.

== Known Issues

=== Updating to {productname} {productmajor}

In-place upgrades from earlier versions or from Beta 4 version to the generally available release is not supported.
We recommend standing up a new cluster and redeploying workloads. For customers with
production servers that cannot be redeployed, contact SUSE Consulting Services or your
account team for further information.

=== Parallel Deployment

To avoid fails, avoid parallel deployment of nodes.
Joining master or worker nodes to an existing cluster should be done serially,
meaning the nodes have to be added separately one after another.
This issue will be fixed in the next release.

include::common.adoc[Common sections]

include::legal.adoc[Legal Notices]
