
include::attributes.adoc[]
include::entities.adoc[]

= {productname} {productversion} Release Notes

ifeval::['{release_type}' != 'public']
[WARNING]
!!! This is a preview release. Not to be distributed outside of SUSE !!!
endif::[]

{productname} is an enterprise-ready Kubernetes-based container management solution

These release notes are updated periodically. The latest version is always available at https://documentation.suse.com/suse-caasp/4/.

[WARNING]
This software is not ready for production use.

[NOTE]
The released version is {productname} {productversion}


== About the Release Notes

The most recent version of the Release Notes is available online at https://www.suse.com/releasenotes.

Entries can be listed multiple times if they are important and belong to multiple sections.

Release notes usually only list changes that happened between two subsequent releases. Certain important entries from the release notes documents of previous product versions may be repeated. To make such entries easier to identify, they contain a note to that effect.

== {productname}

{productname} is an enterprise-ready {kube}-based container management solution used by application development and DevOps teams to more easily and efficiently deploy and manage containerized applications and services. Enterprises use {productname} to reduce application delivery cycle times and improve business agility.

== Supported Platforms

This release supports deployment on:

* {soc} 8
* VMWare ESXi {vmware_version}
* Bare metal
+
({productname} {productversion} supports hardware that is certified for {slsa}
through the YES certification program. You will find a database of certified
hardware at https://www.suse.com/yessearch/.)


== What Is New

=== Base Operating System Is Now {slsa} 15 SP1

The previous version used a minimal OS image called MicroOS. {productname}
{productmajor} uses standard {slsa} 15 SP1 as the base platform OS.
{productname} can be installed as an extension on top of that. Because {slsa} 15 is
designed to address both cloud-native and legacy workloads,
these changes make it easier for customers who want to modernize their
infrastructure by moving existing workloads to a {kube} framework.

Transactional updates are available in {slsa} 15 SP1 as a technical preview but {productname}
{productmajor} will initially ship without the transactional-update mechanism enabled.
The regular zypper workflow allows use of interruption-free node reboot.
The {slsa} update process should help customers integrate a {kube} platform
into their existing operational infrastructure more easily, nevertheless transactional
updates are still the preferred process for some customers,
which is why we provide both options.

=== Software Now Shipped as Packages Instead of Disk Image

In the previous version, the deployment of the software was done by downloading and installing a disk
image with a pre-baked version of the product. In {productname} {productmajor}, the software is distributed
as RPM packages from an extension module in {slsa} 15 SP1.
This adaptation towards containers and {sls} mainly gives customers more deployment flexibility.

=== More Containerized Components

We moved more of the components into containers, namely all the control plane components:
`etcd`, `kube-apiserver`, `kube-controller-manager`, and `kube-scheduler`.
The only pieces that are now running uncontainerized are `CRI-O`, `kubelet` and `kubeadm`.

=== New Deployment Methods

We are using a combination of `skuba` (custom wrapper around kubeadm) and
HashiCorp Terraform to deploy {productname} machines and clusters.
We provide Terraform state examples that you can modify to roll out clusters.

Deployment on bare metal using AutoYaST has now also been tested and documented:
 https://susedoc.github.io/doc-caasp/beta/caasp-deployment/single-html/#_deployment_on_bare_metal

[NOTE]
You must deploy a load balancer manually.
This is currently not possible by using terraform.
You can find an example of a possible load balancer configuration
based on {sle} 15 SP1 and nginx in the __{productname} Deployment Guide__:
 https://susedoc.github.io/doc-caasp/beta/caasp-deployment/single-html/#_load_balancer


=== Updates Using Kured

Updates are implemented with `skuba-update`, that makes use of the `kured`
tool and the SLE package manager. This is implemented in the skuba-update
tool which glues zypper and the kured tool (https://github.com/weaveworks/kured).
Kured (KUbernetes REboot Daemon) is a {kube} daemonset that performs safe
automatic node reboots when the need to do so is indicated by the package
management system of the underlying OS. Automatic updates can be manually
disabled and configured: https://susedoc.github.io/doc-caasp/beta/caasp-admin/single-html/#_cluster_updates



=== Changes to the {kube} Stack

==== Updated Kubernetes

{productname} {productversion} ships with {kube} {kube_version}.
This latest version mainly contains enhancements to core {kube} APIs:
CustomResourceDefinitions Pruning, -Defaulting and -OpenAPI Publishing.
cluster life cycle stability and usability has been enhanced
(`kubeadm init` and `kubeadm join` can now be used to configure and deploy an HA control plane)
and new functionality of the Container Storage Interface (volume cloning) is available.
Read up about the details of the new features of {kube} {kube_version} here:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#115-whats-new


==== CRI-O Replaces Docker

{productname} now uses CRI-O {crio_version} as the default container runtime.
CRI-O is a container runtime interface based on the OCI standard technology.
The choice of CRI-O allows us to pursue our open-source agenda better than competing technologies.

CRI-O's simplified architecture is tailored explicitly for {kube} and has a reduced footprint but also
guarantees full compatibility with existing customer images thanks to its adherence to OCI standards.
Other than Docker, CRI-O allows to update the container runtime without stopping workloads;
providing improved flexibility and maintainabilitty to all {productname} users.

We will strive to maintain {productname}'s compatibility with the Docker Engine in the future.

==== Cilium Replaces Flannel

{productname} now uses Cilium {cilium_version} as the Container Networking
Interface enabling networking policy support.


=== Centralized Logging

The deployment of a Centralized Logging node is now supported for the purpose of
aggregating logs from all the nodes in the {kube} cluster.
Centralized Logging forwards system and {kube} cluster logs to a
specified external logging service, specifically the Rsyslog server,
using {kube} Metadata Module - `mmkubernetes`.


=== Obsolete Components

==== Salt

Orchestration of the cluster no longer relies on Salt.
Orchestration is instead achieved with `kubeadm` and `skuba`.

==== Admin Node / Velum

The admin node is no longer necessary. The cluster will now be controlled
by the master nodes and through API with `skuba` on any {sle} system, such as a local workstation.
This also means the Velum dashboard is no longer available.

== Known Issues

=== Updating to {productname} {productmajor}

In-place upgrades from earlier versions or from Beta 4 version to the generally available release is not supported.
We recommend standing up a new cluster and redeploying workloads. For customers with
production servers that cannot be redeployed, contact SUSE Consulting Services or your
account team for further information.

=== Parallel Deployment

To avoid fails, avoid parallel deployment of nodes.
Joining master or worker nodes to an existing cluster should be done serially,
meaning the nodes have to be added separately one after another.
This issue will be fixed in the next release.


=== Other Known Issues

* https://bugzilla.suse.com/show_bug.cgi?id=1148988 - Joining worker nodes in parallel fails with increasing node count
* https://bugzilla.suse.com/show_bug.cgi?id=1149605 - Kernel-default-base from JeOS lacks support for connecting to SES/ceph cluster
* https://bugzilla.suse.com/show_bug.cgi?id=1149242 - Worker fails to join if node was previously attempted to be deployed as Master
* https://bugzilla.suse.com/show_bug.cgi?id=1145301 - Upgrading a node should trigger a drain
* https://bugzilla.suse.com/show_bug.cgi?id=1145568 - [remove-node] failed disarming kubelet due to 63 characters limitation
* https://bugzilla.suse.com/show_bug.cgi?id=1145773 - Server can't halt/reboot when Ceph RBD volume are mapped
* https://bugzilla.suse.com/show_bug.cgi?id=1144991 - ceph-common, xfsprogs, nfs-client should be installed by default or configurable in skuba
* https://bugzilla.suse.com/show_bug.cgi?id=1137879 - All cilium pods are terminated & replaced after adding worker node
* https://bugzilla.suse.com/show_bug.cgi?id=1137628 - Multiple coredns containers running on master node.


include::common.adoc[Common sections]

include::legal.adoc[Legal Notices]
