include::attributes.adoc[]
include::entities.adoc[]

= {productname} {productversion} Release Notes

{productname} is an enterprise-ready {kube}-based container management solution.

== About the Release Notes

// for beta release:
// The most recent version of the Release Notes is available online at https://susedoc.github.io/caasp-release-notes/beta/release-notes/single-html/.

// for public release:
The most recent version of the Release Notes is available online at https://www.suse.com/releasenotes or https://documentation.suse.com/suse-caasp/4/.

Entries can be listed multiple times if they are important and belong to multiple sections.

Release notes usually only list changes that happened between two subsequent releases.
Certain important entries from the release notes documents of previous product versions may be repeated.
To make such entries easier to identify, they contain a note to that effect.


// Release specific files, latest on top!
include::release-4.2.1.adoc[Release 4.2.1]

include::release-4.2.0.adoc[Release 4.2.0]

include::release-4.1.2.adoc[Release 4.1.2]

include::release-4.1.1.adoc[Release 4.1.1]

include::release-4.1.0.adoc[Release 4.1.0]

include::release-4.0.3.adoc[Release 4.0.3]

include::release-4.0.2.adoc[Release 4.0.2]

include::release-4.0.1.adoc[Release 4.0.1]

include::release-4.0.0.adoc[Release 4.0.0]

// Other includes
include::common.adoc[Common sections]

include::legal.adoc[Legal Notices]
