
include::attributes.adoc[]
include::entities.adoc[]

= {productname} {productversion} Release Notes

{productname} is an enterprise-ready Kubernetes-based container management solution.

== About the Release Notes

// for beta release:
// The most recent version of the Release Notes is available online at https://susedoc.github.io/caasp-release-notes/beta/release-notes/single-html/.

// for public release:
The most recent version of the Release Notes is available online at https://www.suse.com/releasenotes or https://documentation.suse.com/suse-caasp/4/.

Entries can be listed multiple times if they are important and belong to multiple sections.

Release notes usually only list changes that happened between two subsequent releases. Certain important entries from the release notes documents of previous product versions may be repeated. To make such entries easier to identify, they contain a note to that effect.

== Changes in 4.0.3

* Prometheus and Grafana: official monitoring solution for {productname}
* Airgap: format change of https://documentation.suse.com/external-tree/en-us/suse-caasp/4/skuba-cluster-images.txt
* 389-ds fixes (see below)
* skuba fixes (see below)

=== Prometheus and Grafana: official monitoring solution for {productname}
Prometheus and Grafana were already link:https://documentation.suse.com/suse-caasp/4.0/html/caasp-admin/_monitoring.html#_monitoring_stack[documented] but based on upstream helm charts and containers.


In version {productversion}, official SUSE helm carts and containers are now available in the helm chart repository (`+kubernetes-charts.suse.com+`) and the container registry (`+registry.suse.com+`).

=== Airgap: Format change

The format of https://documentation.suse.com/external-tree/en-us/suse-caasp/4/skuba-cluster-images.txt was changed to be able to express more data.
Specifically to add skuba and {productname} versions, so that one can match the images that should be pulled with the respective version.

This way, you can run air gapped production and staging clusters with different {productname} versions.

=== Required Actions

==== Prometheus and Grafana installation instructions

You will need to use `helm` and `kubectl` to deploy Prometheus and Grafana.
Refer to: link:https://documentation.suse.com/suse-caasp/4.0/html/caasp-admin/_monitoring.html#_monitoring_stack[Monitoring chapter in the {productname} admin guide]

==== 389-ds update instructions

`389-ds` containers have been updated in `+registry.suse.com+` (see Bugs fixed below).
In order to deploy your `389-ds` container, see link:https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_configuring_an_external_ldap_server[Configuring and external ldap server at the {productname} admin guide]

==== skuba update instructions

Update skuba on your management workstation as you would do with any other package.

Refer to: link:https://documentation.suse.com/sles/15-SP1/single-html/SLES-admin/#sec-zypper-softup[{sls} 15 SP1 Admin Guide: Updating Software with Zypper]

=== Documentation changes

* Updated monitoring documentation in the admin guide to reflect official charts/containers for monitoring stack
* Added/Updated information about `389-ds` deployment and configuration
* Added information about subnet sizing to deployment guide system requirements
* Unified use of placeholders in code examples to `<PLACEHOLDER>` format
* Added information on using a cluster wide root CA to admin guide
* Add note about NTP client requirement for management workstation
* Various minor formatting and wording fixes

=== Bugs fixed in 4.0.3 since 4.0.2

* link:https://bugzilla.suse.com/show_bug.cgi?id=1156667[bsc#1156667] [Prometheus and Grafana] - User "system:serviceaccount:monitoring:prometheus-kube-state-metrics" cannot list resource
* link:https://bugzilla.suse.com/show_bug.cgi?id=1140533[bsc#1140533] [Prometheus and Grafana] -  Prometheus and grafana images and helm charts on registry.suse.com
* link:https://bugzilla.suse.com/show_bug.cgi?id=1155173[bsc#1155173] [skuba] - skuba node upgrade does not really upgrade node successfully
* link:https://bugzilla.suse.com/show_bug.cgi?id=1151689[bsc#1151689] [skuba] -  Default verbosity hides most errors
* link:https://bugzilla.suse.com/show_bug.cgi?id=1151340[bsc#1151340] [389-ds] - ERR - add_new_slapd_process - Unable to start slapd because it is already running as process 8
* link:https://bugzilla.suse.com/show_bug.cgi?id=1151343[bsc#1151343] [389-ds] - The config /etc/dirsrv/slapd-*/dse.ldif can not be accessed. Attempting restore
* link:https://bugzilla.suse.com/show_bug.cgi?id=1151414[bsc#1151414] [389-ds] - NOTICE - dblayer_start - Detected Disorderly Shutdown last time Directory Server was running, recovering database.
* link:https://bugzilla.suse.com/show_bug.cgi?id=1157332[bsc#1157332] [patterns-caasp] - caasp-release rpm not installed - probably should be included in the patterns?
