include::attributes.adoc[]
include::entities.adoc[]

= {productname} {productversion} Release Notes

{productname} is an enterprise-ready Kubernetes-based container management solution.

== About the Release Notes

// for beta release:
// The most recent version of the Release Notes is available online at https://susedoc.github.io/caasp-release-notes/beta/release-notes/single-html/.

// for public release:
The most recent version of the Release Notes is available online at https://www.suse.com/releasenotes or https://documentation.suse.com/suse-caasp/4/.

Entries can be listed multiple times if they are important and belong to multiple sections.

Release notes usually only list changes that happened between two subsequent releases.
Certain important entries from the release notes documents of previous product versions may be repeated.
To make such entries easier to identify, they contain a note to that effect.

== Changes in 4.1.0

=== {kube} update

{productname} now ships with {kube} {kube_version}.
Most of the significant changes relate to this upgrade, as more than 31 enhancements were merged in the {kube} {kube_version} release.
You can read a short summary of the changes under <<kubernetes_updates>>.
Manual actions are required for 4.1.0 release.

=== Helm security update

Moreover, helm has been updated to fix a security issue (link:https://www.suse.com/security/cve/CVE-2019-18658/[CVE-2019-18658]).

=== Stratos, a web console for {kube}

Stratos is now available as tech preview for {productname}. Stratos is a
web console for {kube} and for Cloud Foundry.
A single instance of Stratos can be used to monitor and interact with different
{kube} clusters as long as their API endpoints are reachable by Stratos.

Stratos integrates with Prometheus: it can scrape metrics collected
by Prometheus and show them using pre-built charts.

Finally Stratos can be used to interact with helm chart repositories. It can
show the charts available and install them straight from its web interface.
It can also show all the workloads that are running on a {kube} that have
been created by helm chart.

**Note well:** the helm chart integration is a tech preview feature of Stratos
that must be enabled at deployment time.

=== Required Actions

==== Skuba and helm update Instructions

Update skuba and helm on your management workstation as you would do with any other package.

Refer to: link:https://documentation.suse.com/sles/15-SP1/single-html/SLES-admin/#sec-zypper-softup-update[https://documentation.suse.com/sles/15-SP1/single-html/SLES-admin/#sec-zypper-softup-update]

[WARNING]
====
When running helm-init you may hit a link:https://bugzilla.suse.com/show_bug.cgi?id=1159047[known bug on the certificate validation]:

----
https://kubernetes-charts.storage.googleapis.com is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: x509: certificate signed by unknown authority
----

In order to fix this, run:

----
sudo update-ca-certificates
----

====


After updating helm to latest version on the management host, you have to also upgrade the helm-tiller image in the cluster, by running:

----
helm init \
    --tiller-image registry.suse.com/caasp/v4/helm-tiller:2.16.1 \
    --service-account tiller --upgrade
----


==== Upgrade Your {kube} Cluster

Use skuba to upgrade your {kube} cluster as link:https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#handling_updates[documented in the Administration guide].

[WARNING]
====
Please, do not run `zypper patch` manually on your nodes.
If you do, you will see an error about a conflict when patching {crio}.
This is expected, because the patch is not supposed to be installed this way.

Instead, cluster updates are being handled by skuba as link:{docurl}caasp-admin/#handling_updates[documented in the Administration guide].
====

==== Update Your {kube} Manifests for {kube} {kube_version}:

Some API resources are moved to stable, while others have been
moved to different groups or deprecated.

The following will impact your deployment manifests:

*  ``DaemonSet``, ``Deployment``, ``StatefulSet``, and ``ReplicaSet`` in
  ``extensions/`` (both ``v1beta1`` and ``v1beta2``) is deprecated.
  Migrate to ``apps/v1`` group instead for all those objects.
  Please note that ``kubectl convert`` can help you migrate all the
  necessary fields.
*  ``PodSecurityPolicy`` in ``extensions/v1beta1`` is deprecated. Migrate to
  ``policy/v1beta1`` group for ``PodSecurityPolicy``.
  Please note that ``kubectl convert`` can help you migrate all the
  necessary fields.
*  ``NetworkPolicy`` in ``extensions/v1beta1`` is deprecated. Migrate to
  ``networking.k8s.io/v1`` group for ``NetworkPolicy``.
  Please note that ``kubectl convert`` can help you migrate all the
  necessary fields.
*  ``Ingress`` in ``extensions/v1beta1`` is being phased out. Migrate to
  ``networking.k8s.io/v1beta1`` as soon as possible.
  This new API does not need to update other API fields and therefore
  only a path change is necessary.
*  Custom resource definitions have moved from ``apiextensions.k8s.io/v1beta1``
  to ``apiextensions.k8s.io/v1``.

Please also see https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ for more details.



=== Bugs Fixed in 4.1.0 since 4.0.3

* link:https://bugzilla.suse.com/show_bug.cgi?id=1144065[bsc#1144065] [cri-o] - (link:https://www.suse.com/security/cve/CVE-2019-10214[CVE-2019-10214]) VUL-0: CVE-2019-10214: libcontainers-common: library does not enforce TLS connections
* link:https://bugzilla.suse.com/show_bug.cgi?id=1118898[bsc#1118898] [cri-o] - (link:https://www.suse.com/security/cve/CVE-2018-16874[CVE-2018-16874]) VUL-0: CVE-2018-16874: go: cmd/go: directory traversal
* link:https://bugzilla.suse.com/show_bug.cgi?id=1100838[bsc#1100838] [cri-o] - cri-o does not block /proc/acpi pathnames (i.e., also affected by (link:https://www.suse.com/security/cve/CVE-2018-10892[CVE-2018-10892]))
* link:https://bugzilla.suse.com/show_bug.cgi?id=1118897[bsc#1118897] [etcd] - (link:https://www.suse.com/security/cve/CVE-2018-16873[CVE-2018-16873]) VUL-0: CVE-2018-16873: go: cmd/go: remote command execution
* link:https://bugzilla.suse.com/show_bug.cgi?id=1118899[bsc#1118899] [etcd] - (link:https://www.suse.com/security/cve/CVE-2018-16875[CVE-2018-16875]) VUL-0: CVE-2018-16875: go: crypto/x509: CPU denial of service
* link:https://bugzilla.suse.com/show_bug.cgi?id=1156646[bsc#1156646] [helm] - (link:https://www.suse.com/security/cve/CVE-2019-18658[CVE-2019-18658]) VUL-0: CVE-2019-18658: helm: commands that deal with loading a chart as a directory or packaging a chart provide an opportunity for a maliciously designed chart to include sensitive content such as /etc/passwd
* link:https://bugzilla.suse.com/show_bug.cgi?id=1152861[bsc#1152861] [kubernetes] - (link:https://www.suse.com/security/cve/CVE-2019-11253[CVE-2019-11253]) VUL-0: CVE-2019-11253: kubernetes: YAML parsing vulnerable to "Billion Laughs" attack, allowing for remote denial of service
* link:https://bugzilla.suse.com/show_bug.cgi?id=1146991[bsc#1146991] [kubernetes] - BPF filesystem is not mounted, possible downtime when cilium pods are restarted
* link:https://bugzilla.suse.com/show_bug.cgi?id=1147142[bsc#1147142] [kubernetes] - Update golang/x/net dependency to bring in fixes for (link:https://www.suse.com/security/cve/CVE-2019-9512[CVE-2019-9512]), (link:https://www.suse.com/security/cve/CVE-2019-9514[CVE-2019-9514])
* link:https://bugzilla.suse.com/show_bug.cgi?id=1143813[bsc#1143813] [kubernetes] - kubelet sometimes starting too fast
* link:https://bugzilla.suse.com/show_bug.cgi?id=1143813[bsc#1143813] [skuba] - CaaSP SSL / PKI / CA Infrastructure unclear and probably inconsistent and wrong?
* link:https://bugzilla.suse.com/show_bug.cgi?id=1152335[bsc#1152335] [supportutils-plugin-suse-caasp] - supportconfig adjustments for CaaSP v4 missing

=== Documentation Updates

* Switched examples to use SUSE supported helm, Prometheus, nginx-ingress and Grafana charts and images
* link:{docurl}caasp-admin/single-html/_security.html#_deployment_with_a_custom_ca_certificate[Added instructions on how to replace {kube} certificates with custom CA certificate]
* link:{docurl}caasp-admin/single-html/_security.html#_replace_server_certificate_signed_by_a_trusted_ca_certificate[Added instructions to configure custom certificates for gangway and dex]
* link:{docurl}caasp-admin/single-html/_software_management.html#_installing_tiller[Added instructions for secured Tiller deployment]
* link:{docurl}caasp-deployment/single-html/#machine-id[Added notes about unique `machine-id` requirement]
* link:{docurl}caasp-deployment/single-html/#_autoyast_preparation[Added timezone configuration example for {ay}]
* link:https://github.com/SUSE/doc-caasp/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc[Various minor bugfixes and improvements]

=== Known issue: skuba upgrade could not parse "Unknown" as version ====

Running "skuba node upgrade plan" might fail with the error "could not parse "Unknown" as version" when a worker, after running "skuba node upgrade apply", had not fully started yet.

If you are running into this issue, please add some delay after running "skuba node upgrade apply" and prior to running "skuba node upgrade plan".

This is tracked in link:https://bugzilla.suse.com/show_bug.cgi?id=1159452[bsc#1159452]


== Changes in 4.0.3

* Prometheus and Grafana: official monitoring solution for {productname}
* Airgap: format change of https://documentation.suse.com/external-tree/en-us/suse-caasp/4/skuba-cluster-images.txt
* 389-ds fixes (see below)
* skuba fixes (see below)

=== Prometheus and Grafana: official monitoring solution for {productname}
Prometheus and Grafana were already link:https://documentation.suse.com/suse-caasp/4.0/html/caasp-admin/_monitoring.html#_monitoring_stack[documented] but based on upstream helm charts and containers.

In version {productversion}, official SUSE helm carts and containers are now available in the helm chart repository (`+kubernetes-charts.suse.com+`) and the container registry (`+registry.suse.com+`).

=== Airgap: Format Change

The format of https://documentation.suse.com/external-tree/en-us/suse-caasp/4/skuba-cluster-images.txt was changed to be able to express more data.
Specifically to add skuba and {productname} versions, so that one can match the images that should be pulled with the respective version.

This way, you can run air gapped production and staging clusters with different {productname} versions.

=== Required Actions

==== Skuba Update Instructions

Update skuba on your management workstation as you would do with any other package.

Refer to: link:https://documentation.suse.com/sles/15-SP1/single-html/SLES-admin/#sec-zypper-softup[{sls} 15 SP1 Admin Guide: Updating Software with Zypper]

==== Prometheus and Grafana Installation Instructions

You will need to use `helm` and `kubectl` to deploy Prometheus and Grafana.
Refer to: link:https://documentation.suse.com/suse-caasp/4.0/html/caasp-admin/_monitoring.html#_monitoring_stack[Monitoring chapter in the {productname} admin guide]

==== 389-ds Update Instructions

`389-ds` containers have been updated in `+registry.suse.com+` (see Bugs fixed below).
In order to deploy your `389-ds` container, see link:https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_configuring_an_external_ldap_server[Configuring and external ldap server at the {productname} admin guide]

=== Documentation Changes

* link:https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-admin/#_monitoring_stack[Updated monitoring documentation in the admin guide to reflect official charts/containers for monitoring stack]
* link:https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-admin#_deploying_an_external_389_directory_server[Added/Updated information about `389-ds` deployment and configuration]
* link:https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-deployment/#_networking[Added information about subnet sizing to deployment guide system requirements]
* link:https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-admin/#_deployment_with_a_custom_ca_certificate[Added information on using a cluster wide root CA to admin guide]
* link:https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-deployment/#_management_workstation[Add note about NTP client requirement for management workstation]
* link:https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-deployment/#_configuring_the_load_balancer[Added less aggressive nginx timeout values to examples]
* Unified use of placeholders in code examples to `<PLACEHOLDER>` format
* Various minor formatting and wording fixes

=== Bugs Fixed in 4.0.3 since 4.0.2

* link:https://bugzilla.suse.com/show_bug.cgi?id=1156667[bsc#1156667] [Prometheus and Grafana] - User "system:serviceaccount:monitoring:prometheus-kube-state-metrics" cannot list resource
* link:https://bugzilla.suse.com/show_bug.cgi?id=1140533[bsc#1140533] [Prometheus and Grafana] -  Prometheus and grafana images and helm charts on registry.suse.com
* link:https://bugzilla.suse.com/show_bug.cgi?id=1155173[bsc#1155173] [skuba] - skuba node upgrade does not really upgrade node successfully
* link:https://bugzilla.suse.com/show_bug.cgi?id=1151689[bsc#1151689] [skuba] -  Default verbosity hides most errors
* link:https://bugzilla.suse.com/show_bug.cgi?id=1151340[bsc#1151340] [389-ds] - ERR - add_new_slapd_process - Unable to start slapd because it is already running as process 8
* link:https://bugzilla.suse.com/show_bug.cgi?id=1151343[bsc#1151343] [389-ds] - The config /etc/dirsrv/slapd-*/dse.ldif can not be accessed. Attempting restore
* link:https://bugzilla.suse.com/show_bug.cgi?id=1151414[bsc#1151414] [389-ds] - NOTICE - dblayer_start - Detected Disorderly Shutdown last time Directory Server was running, recovering database.
* link:https://bugzilla.suse.com/show_bug.cgi?id=1157332[bsc#1157332] [patterns-caasp] - caasp-release rpm not installed - probably should be included in the patterns?

== Changes in 4.0.2

[NOTE]
====
Core addons are addons deployed automatically by `skuba` when you bootstrap a cluster. Namely:

* Cilium
* Dex
* Gangway
* Kured
* Default Pod Security Policies (PSP's)
====

* `skuba addon` command has been introduced to handle core addons
** `skuba addon upgrade plan` will inform about what core addons will be upgraded
** `skuba addon upgrade apply` will upgrade core addons in the current cluster

[[required-actions-402]]
=== Required Actions

* When using `skuba addon upgrade apply`, all settings of all addons will be reverted to the defaults. Make sure to reapply your changes after running `skuba addon upgrade apply`, had you modified the default settings of core addons.

=== Bugs fixed in 4.0.2 since 4.0.1

* link:https://bugzilla.suse.com/show_bug.cgi?id=1145568[bsc#1145568] [remove-node] failed disarming kubelet due to 63 character limitation
* link:https://bugzilla.suse.com/show_bug.cgi?id=1145907[bsc#1145907] LB dies when removing a master node in VMWare
* link:https://bugzilla.suse.com/show_bug.cgi?id=1146774[bsc#1146774] AWS: pod to service connectivity broken in certain cases
* link:https://bugzilla.suse.com/show_bug.cgi?id=1148090[bsc#1148090] Multinode cluster upgrade fails on 2nd master due to TLS handshake timeout
* link:https://bugzilla.suse.com/show_bug.cgi?id=1148412[bsc#1148412] Gangway uses CSS stylesheet from cloudflare.com
* link:https://bugzilla.suse.com/show_bug.cgi?id=1148524[bsc#1148524] Allow easy recovery from bootstrap failed during add-ons deployment phase
* link:https://bugzilla.suse.com/show_bug.cgi?id=1148700[bsc#1148700] worker node upgrade needs to use kubeletVersion in nodeVersionInfoUpdate type
* link:https://bugzilla.suse.com/show_bug.cgi?id=1149637[bsc#1149637] Misspelling of bootstrapping in a common error message
* link:https://bugzilla.suse.com/show_bug.cgi?id=1153913[bsc#1153913] Can not bootstrap an new cluster if a valid `kubectl` config is present
* link:https://bugzilla.suse.com/show_bug.cgi?id=1153928[bsc#1153928] Reboot can be triggered before skuba-update finishes
* link:https://bugzilla.suse.com/show_bug.cgi?id=1154085[bsc#1154085] skuba node upgrade shows component downgrade
* link:https://bugzilla.suse.com/show_bug.cgi?id=1154754[bsc#1154754] oauth2: cannot fetch token after 24 hours

== Changes in 4.0.1

* Updated Gangway container image (see <<required-actions-401>>)
* Added link:https://documentation.suse.com/suse-caasp/4/single-html/caasp-deployment/#_airgapped_deployment[air gap deployment instructions]
* Various bug fixes and improvements

[[required-actions-401]]
=== Required Actions

[[gangway-update]]
==== Update the Gangway Image

The gangway image that shipped with {productname} 4.0 must be updated manually by performing the following step:

====
kubectl set image deployment/oidc-gangway \
    oidc-gangway=registry.suse.com/caasp/v4/gangway:3.1.0-rev4 \
    --namespace kube-system
====

== Known Issues

You must update the gangway container image manually after update (see <<required-actions-401>> ).

For a full list of Known Issues refer to: link:{bugzilla_url}[Bugzilla].

== Supported Platforms

This release supports deployment on:

* {soc} 8
* VMWare ESXi {vmware_version}
* Bare metal
+
({productname} {productversion} supports hardware that is certified for {slsa}
through the YES certification program. You will find a database of certified
hardware at https://www.suse.com/yessearch/.)

== What Is New

=== Base Operating System Is Now {slsa} 15 SP1

The previous version used a minimal OS image called MicroOS. {productname}
{productmajor} uses standard {slsa} 15 SP1 as the base platform OS.
{productname} can be installed as an extension on top of that. Because {slsa} 15 is
designed to address both cloud-native and legacy workloads,
these changes make it easier for customers who want to modernize their
infrastructure by moving existing workloads to a {kube} framework.

Transactional updates are available in {slsa} 15 SP1 as a technical preview but {productname}
{productmajor} will initially ship without the transactional-update mechanism enabled.
The regular zypper workflow allows use of interruption-free node reboot.
The {slsa} update process should help customers integrate a {kube} platform
into their existing operational infrastructure more easily, nevertheless transactional
updates are still the preferred process for some customers,
which is why we provide both options.

=== Software Now Shipped as Packages Instead of Disk Image

In the previous version, the deployment of the software was done by downloading and installing a disk
image with a pre-baked version of the product. In {productname} {productmajor}, the software is distributed
as RPM packages from an extension module in {slsa} 15 SP1.
This adaptation towards containers and {sls} mainly gives customers more deployment flexibility.

=== More Containerized Components

We moved more of the components into containers, namely all the control plane components:
`etcd`, `kube-apiserver`, `kube-controller-manager`, and `kube-scheduler`.
The only pieces that are now running uncontainerized are `CRI-O`, `kubelet` and `kubeadm`.

=== New Deployment Methods

We are using a combination of `skuba` (custom wrapper around kubeadm) and
HashiCorp Terraform to deploy {productname} machines and clusters.
We provide Terraform state examples that you can modify to roll out clusters.

Deployment on bare metal using AutoYaST has now also been tested and documented:
link:https://documentation.suse.com/suse-caasp/4/single-html/caasp-deployment/#deployment_bare_metal[]

[NOTE]
You must deploy a load balancer manually.
This is currently not possible using Terraform.
Find example load balancer configurations
based on {sle} 15 SP1 and Nginx or HAProxy in the __{productname} Deployment Guide__:
https://documentation.suse.com/suse-caasp/4/single-html/caasp-deployment/#_load_balancer[]

=== Updates Using Kured

Updates are implemented with `skuba-update`, that makes use of the `kured`
tool and the SLE package manager. This is implemented in the skuba-update
tool which glues zypper and the kured tool (https://github.com/weaveworks/kured).
Kured (KUbernetes REboot Daemon) is a {kube} daemonset that performs safe
automatic node reboots when the need to do so is indicated by the package
management system of the underlying OS. Automatic updates can be manually
disabled and configured: https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#_cluster_updates

=== Automatic Installation of Packages For Storage Backends Discontinued

In previous versions {productname} would ship with packages to support all available storage backends.
This negated the minimal install size approach and is discontinued. If you require a specific software
package for your storage backend please install it using {ay}, {tf} or `zypper`.
Refer to: https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#_software_management


[[kubernetes_updates]]
=== Changes to the {kube} Stack

==== Updated Kubernetes

{productname} {productversion} ships with {kube} {kube_version}.

{kube} version 1.16 contains the following notable changes:

* Custom Resources Definitions (CRD) are out of the beta version and are
  generally available in the `apiextensions.k8s.io/v1` group.
* IPv4/IPv6 dual stack is officially in alpha.
Read up about the details of the new features of {kube} 1.16 here:
https://kubernetes.io/blog/2019/09/18/kubernetes-1-16-release-announcement/.

{kube} version 1.15 mainly contains enhancements to core {kube} APIs:

* CustomResourceDefinitions Pruning, -Defaulting and -OpenAPI Publishing.
* cluster life cycle stability and usability has been enhanced
  (`kubeadm init` and `kubeadm join` can now be used to configure and deploy an HA control plane)
* new functionality of the Container Storage Interface (volume cloning) is available.
Read up about the details of the new features of {kube} 1.15 here:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#115-whats-new

==== CRI-O Replaces Docker

{productname} now uses CRI-O {crio_version} as the default container runtime.
CRI-O is a container runtime interface based on the OCI standard technology.
The choice of CRI-O allows us to pursue our open-source agenda better than competing technologies.

CRI-O's simplified architecture is tailored explicitly for {kube} and has a reduced footprint but also
guarantees full compatibility with existing customer images thanks to its adherence to OCI standards.
Other than Docker, CRI-O allows to update the container runtime without stopping workloads;
providing improved flexibility and maintainabilitty to all {productname} users.

We will strive to maintain {productname}'s compatibility with the Docker Engine in the future.

==== Cilium Replaces Flannel

{productname} now uses Cilium {cilium_version} as the Container Networking
Interface enabling networking policy support.

=== Centralized Logging

The deployment of a Centralized Logging node is now supported for the purpose of
aggregating logs from all the nodes in the {kube} cluster.
Centralized Logging forwards system and {kube} cluster logs to a
specified external logging service, specifically the Rsyslog server,
using {kube} Metadata Module - `mmkubernetes`.


=== Obsolete Components

==== Salt

Orchestration of the cluster no longer relies on Salt.
Orchestration is instead achieved with `kubeadm` and `skuba`.

==== Admin Node / Velum

The admin node is no longer necessary. The cluster will now be controlled
by the master nodes and through API with `skuba` on any {sle} system, such as a local workstation.
This also means the Velum dashboard is no longer available.

== Known Issues

=== Updating to {productname} {productmajor}

In-place upgrades from earlier versions or from Beta 4 version to the generally available release is not supported.
We recommend standing up a new cluster and redeploying workloads. For customers with
production servers that cannot be redeployed, contact SUSE Consulting Services or your
account team for further information.

=== Parallel Deployment

To avoid fails, avoid parallel deployment of nodes.
Joining master or worker nodes to an existing cluster should be done serially,
meaning the nodes have to be added separately one after another.
This issue will be fixed in the next release.

include::common.adoc[Common sections]

include::legal.adoc[Legal Notices]
