
include::attributes.adoc[]
include::entities.adoc[]

= {productname} {productversion} Release Notes

ifeval::['{release_type}' != 'public']
[WARNING]
!!! This is a preview release. Not to be distributed outside of SUSE !!!
endif::[]

[WARNING]
This software is not ready for production use.

[NOTE]
The released version is {productname} {productversion}


== Supported Platforms

This release supports deployment on

* {soc} 8
* VMWare ESXi {vmware_version}
* Bare metal

//Main features of Beta 4: Dex/Gangway, Supportconfig, k8s 1.15

== Changes To Base Os

=== Base Operating System Now Sle15 Sp1

The previous version used a minimal OS image called MicroOS. {productname}
{productmajor} uses standard {sle} Server 15 SP1 as the base platform OS.
CaaSP can be installed as an extension on top of that. Because {slsa} 15 is
designed to address both cloud native and legacy workloads,
these changes make it easier for customers who want to modernize their
infrastructure by moving existing workloads to a {kube} framework.

Transactional-updates are available as a technical preview but {productname}
{productmajor} will initially ship without the transactional-update mechanism enabled.
The regular zypper workflow allows use of interruption free node reboot.
The SLES update process should help customers integrate a Kubernetes platform
into their existing operational infrastructure more easily, nevertheless transactional
updates are still the preferred process for some customers,
which is why we provide both options.

=== Software Now Shipped As Packages Instead Of Disk Image

In the previous version the deployment of the software was done by downloading and installing a disk
image with a pre-baked version of the product. In {productname} {productmajor} the software is distributed
as RPM packages from an extension module in {sle} 15 SP1.
This adaptation towards containers and {sles} mainly gives customers more deployment flexibility.

=== Components Even More Containerized

We moved more of the components into containers, namely all the control plane components:
`etcd`, `kube-apiserver`, `kube-controller-manager` and `kube-scheduler`.
The only pieces that are now running uncontainerized are `CRI-O`, `kubelet` and `kubeadm`.

=== New Deployment Methods

We are using a combination of `skuba` (custom wrapper around kubeadm) and
HashiCorp Terraform to deploy SUSE CaaS Platform machines and clusters.
We provide terraform state examples that you can modify to roll out clusters.

Deployment on Bare metal using AutoYaST has now also been tested and documented:
 https://susedoc.github.io/doc-caasp/beta/caasp-deployment/single-html/#_deployment_on_bare_metal

Note: You must roll out a load balancer manually,
this is currently not possible by using terraform.
Find an example of a possible load balancer configuration
based on SUSE Linux Enterprise 15 SP1 and nginx in the Deployment guide:
 https://susedoc.github.io/doc-caasp/beta/caasp-deployment/single-html/#_load_balancer


=== Updates Using Kured

Updates are implemented with `skuba-update`, that makes use of the `kured`
tool and the SLE package manager. This is implemented in the skuba-update
tool which glues zypper and the kured tool (https://github.com/weaveworks/kured).
Kured (KUbernetes REboot Daemon) is a Kubernetes daemonset that performs safe
automatic node reboots when the need to do so is indicated by the package
management system of the underlying OS. Automatic updates can be manually
disabled and configured: https://susedoc.github.io/doc-caasp/beta/caasp-admin/single-html/#_cluster_updates



== Changes To Kubernetes Stack

=== Updated Kubernetes

{productname} {productversion} ships with {kube} {kube_version}.
This latest version mainly contains enhancements to core {kube} APIs:
CustomResourceDefinitions Pruning, -Defaulting and -OpenAPI Publishing.
cluster life cycle stability and usability has been enhanced
(`kubeadm init` and `kubeadm join` can now be used to configure and deploy an HA control plane)
and new functionality of the Container Storage Interface (volume cloning) is available.
Read up about the details of the new features of {kube} {kube_version} here:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#115-whats-new


=== CRI-O Replaces Docker

{productname} now uses CRI-O {crio_version} as the default container runtime.
CRI-O is a container runtime interface based on the OCI standard technology.
The choice of CRI-O allows us to pursue our open-source agenda better than competing technologies.

CRI-O's simplified architecture is tailored explicitly for {kube} and has a reduced footprint but also
guarantees full compatibility with existing customer images thanks to its adherence to OCI standards.
Other than Docker, CRI-O allows to update the container runtime without stopping workloads;
providing improved flexibility and maintainabilitty to all {productname} users.

We will strive to maintain {productname}'s compatibility with Docker in the future.

=== Cilium Replaces Flannel

{productname} now uses Cilium {cilium_version} as the Container Networking
Interface enabling networking policy support.


== Centralized logging

The deployment of a Centralized Logging node is now supported for the purpose of
aggregating logs from all the nodes in the kubernetes cluster.
Centralized Logging forwards system and Kubernetes cluster logs to a
specified external logging service, specifically the Rsyslog server,
using Kubernetes Metadata Module - `mmkubernetes`.

== Obsolete Components

=== Salt

Orchestration of the cluster no longer relies on Salt.
Orchestration is instead achieved with `kubeadm` and `skuba`.

=== Admin Node / Velum

The Admin Node is no longer necessary. The cluster will now be controlled
by the master nodes and through API with `skuba` on the local workstation.
This also means the Velum dashboard is no longer available.

== Known Issues

=== Layer 7 Policies in Cilium

The current implementation of Cilium in {productname} does not support Layer 7 policies!

=== Renaming `caaspctl` to `skuba`

The `caaspctl` tool has been renamed from it's working title to
`skuba` with the release of {productname} Beta 3.

=== Other Known Issues:

* https://bugzilla.suse.com/show_bug.cgi?id=1138908 - `skuba node remove` removes the node only temporarily until you restart.
* https://bugzilla.suse.com/show_bug.cgi?id=1138859 - Terraform network variables are not interpolated.
* https://bugzilla.suse.com/show_bug.cgi?id=1137879 - All cilium pods are terminated & replaced after adding worker node.
* https://bugzilla.suse.com/show_bug.cgi?id=1138139 - Node removal freezes on drain without timeout.
* https://bugzilla.suse.com/show_bug.cgi?id=1138267 - conntrack binary is missing for kube-proxy.
* https://bugzilla.suse.com/show_bug.cgi?id=1137591 - Failed disarming kubelet during node removal.
* https://bugzilla.suse.com/show_bug.cgi?id=1136960 - Failed to change role from worker to master.
* https://bugzilla.suse.com/show_bug.cgi?id=1137333 - kubernetes-client not present in Management pattern (kubectl).
* https://bugzilla.suse.com/show_bug.cgi?id=1137628 - Multiple coredns containers running on master node.
