== Changes in 4.1.2

=== Deployment on AWS as Technology Preview

Deployment of {productname} on Amazon Web Services (AWS) has been tested and documented.
{tf} is used to deploy the infrastructure and the `skuba` tool to bootstrap the {kube} cluster on top of it.
For detailed instructions please see link:https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-deployment/#_deployment_on_amazon_aws[the Deployment Guide].
Please note that {productname} deployment on AWS may not be functionally complete, and is not intended for production use.

=== Terraform Upgrade

{productname} can now be deployed with *{tf} 0.12*. All details of the new version
can be found in the link:https://www.hashicorp.com/blog/terraform-0-1-2-preview/[HashiCorp Documentation].
The official website for the {tf} 0.12 upgrade is https://www.terraform.io/upgrade-guides/0-12.html.

=== etcd Backup and Restore for Master Nodes Disaster Recovery

* Provide etcd backup process on-demand or on a schedule to prevent etcd data corruption.
* Provide etcd restore process to recover failed master node(s) to restore etcd quorum for cluster serving.

For detailed instructions please see link: https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#_backup_etcd_cluster_data[the Administration Guide].

=== Velero for Disaster Recovery

* Provide Velero as a solution for data protection and data migration by backing up and migrating Kubernetes resources and persistent volumes to and from externally supported storage backend on demand or on a schedule.

For detailed instructions please see link: https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#_disaster_recovery[the Administration Guide].

=== Required Actions

==== Upgrade {tf} Files and State

In order to seamlessly switch to {tf} 0.12 you need to make sure that:

* All files follow the new syntax for the link:https://github.com/hashicorp/hcl[HashiCorp Configuration Language] included in {tf} 0.12
* All boolean values are `true` or `false` and *not* 0 or 1
* All variables are explicitly declared
* All dependencies are explicitly declared to reach the expected behavior

==== Recommended Procedure

Enter your {tf} files/state folder and:

* Install the latest version of {tf} using `zypper in terraform` (the installed version should be 0.12.19)
* Navigate to your {tf} root folder (e.g. `/usr/share/caasp/terraform/vmware`)
* Migrate {tf} files with the automatic migration tool by running `terraform 0.12upgrade`
** For OpenStack, run the <<terraform-openstack-extra-ops>> (see below)
** Run `terraform apply` to update the {tf} definitions to the new format used by 0.12
+
[IMPORTANT]
====
If you do not update the definitions before running {tf} again your output might contain `nil`/`null` strings when you run `terraform refresh` followed by `terraform output`.
This can break automations that are based on the output. Please make sure you have updated/applied all definitions before running {tf}.
====
* Run `zypper up skuba`
* You can then run the `terraform init/plan/apply` commands as usual.

[[terraform-openstack-extra-ops]]
==== Extra Operations for In-place Upgrade of OpenStack {tf} Files

* Replace any boolean values written as a number with `false`/`true`.
  For example, for the variables in `openstack/variables.tf`
  (and their equivalent in your `terraform.tfvars` file), replace
  `default = 0` with `default = false` in the variables
  `workers_vol_enabled` and `dnsentry`. Do the same for
  any extra boolean variable you might have added.
* Introduce a `depends_on` on the resource `"openstack_compute_floatingip_associate_v2" "master_ext_ip"` in `master-instance.tf`:
+
----
depends_on = [openstack_compute_instance_v2.master]
----
+
* Introduce a `depends_on` on the resource `"master_wait_cloudinit"` in `master-instance.tf`:
+
----
depends_on = [
  openstack_compute_instance_v2.master,
  openstack_compute_floatingip_associate_v2.master_ext_ip
]
----
+
* Introduce a `depends_on` on the resources
  `"openstack_compute_floatingip_associate_v2" "worker_ext_ip"` and
  `"null_resource" "worker_wait_cloudinit"` in `worker-instance.tf`, similarly to the ones for master.
  Replace `master` with `worker` in the examples above.
* Update the resources `resource "openstack_compute_instance_v2" "master"`
  and `resource "openstack_compute_instance_v2" "worker"` with
  `master-instance.tf` and `worker-instance.tf` respectively. Add the following resources:
+
----
lifecycle {
  ignore_changes = [user_data]
}
----
+
[NOTE]
====
The above option is needed because {tf} will detect all machines as new resources when `user_data` changes during the upgrade.
====
+
This will make it possible to update your cluster from a {tf} 0.11 state
into a {tf} 0.12 state without tearing it down completely.

[WARNING]
=========
When adding `lifecycle { ignore_change = [user_data] }` in your master and
worker instances, you will effectively prevent updates of nodes, should you or
SUSE update the `user_data`. This should be removed as soon as possible after the
migration to {tf} 0.12.
=========

==== etcdctl
Run `zypper in etcdctl` in the management host to install etcdctl.

==== Update packages for general fixes
Update `skuba` package and `patterns-caasp-Management` on your management workstation as you would do with any other package.

Refer to: link:https://documentation.suse.com/sles/15-SP1/single-html/SLES-admin/#sec-zypper-softup-update[https://documentation.suse.com/sles/15-SP1/single-html/SLES-admin/#sec-zypper-softup-update]

Updating `patterns-caasp-Management` will install the new terraform providers for AWS.

Packages on your cluster nodes (cri-o) will be updated automatically by `skuba-update` link:https://documentation.suse.com/suse-caasp/4.1/html/caasp-admin/_cluster_updates.html#_base_os_updates


=== Bugs Fixed in 4.1.2 since 4.1.1

* link:https://bugzilla.suse.com/show_bug.cgi?id=1161056[bsc#1161056] [cri-o] - Fix upgrade from 4.0.3 to 4.1.0 - skuba node upgrade - fails due to crio-wipe.service not starting
* link:https://bugzilla.suse.com/show_bug.cgi?id=1161179[bsc#1161179] [cri-o] - Fix invalid apparmor profile
* link:https://bugzilla.suse.com/show_bug.cgi?id=1158440[bsc#1158440] [terraform] - Update in SLE-15 (bsc#1158440, CVE-2019-19316)
* link:https://bugzilla.suse.com/show_bug.cgi?id=1148092[bsc#1148092] [terraform] - Include in SLE-15 (bsc#1148092, jsc#ECO-134)
* link:https://bugzilla.suse.com/show_bug.cgi?id=1145003[bsc#1145003] [terraform-provider-openstack] - Update to version 1.19.0
* link:https://bugzilla.suse.com/show_bug.cgi?id=1159082[bsc#1159082] [grafana] - Fix some missing container images of grafana helm chart
* link:https://bugzilla.suse.com/show_bug.cgi?id=1161225[bsc#1161225] [grafana] - Fix grafana helm chart has app version 6.4.2 but version is 6.2.5
* link:https://bugzilla.suse.com/show_bug.cgi?id=1161110[bsc#1161110] [grafana] - Fix Grafana dashboard should not name "CaaSP" but "SUSE (r) CaaS Platform"
* link:https://bugzilla.suse.com/show_bug.cgi?id=1162093[bsc#1162093] [kubelet] - Release fix for volume-plugin-dir in kubernetes packages
* link:https://bugzilla.suse.com/show_bug.cgi?id=1160463[bsc#1160463] [skuba] - Fix skuba-update --version always 0.0.0
* link:https://bugzilla.suse.com/show_bug.cgi?id=1157323[bsc#1157323] [skuba] - Fix need a way to report on current available CaaSP version vs. installed version

[[docs-changes-412]]
=== Documentation Changes

* Added link:https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-deployment/#_deployment_on_amazon_web_services_aws[AWS deployment instructions] (Tech Preview)
* Added link:https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-deployment/#deployment_bare_metal[KVM deployment instructions]
* Improved instructions for Monitoring to link:https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#_monitoring_stack[deploy Grafana in a sub path] and enhanced ingress settings
* Fix unspecific expression in link:https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#alertmanager_configuration_example[AlertManager example]
* Added notes on link:single-html/caasp-admin/#_control_plane_nodes_certificates_rotation[certificate rotation for the control plane]
* Various other fixes and improvements (Refer to: https://github.com/SUSE/doc-caasp/releases)
