== Changes in 4.2.4

=== 'helm3' Package Available

Included in 4.2.4 is a package for Helm 3. This package will not be installed by default but is available for users who prefer to use Helm 3 over the default Helm 2 in the 4.2 releases.

To install Helm 3, use this procedure:

    sudo zypper remove helm
    sudo zypper install helm3

Note the difference in package name, and that both packages cannot be installed at the same time without conflicts.
Further documentation on using Helm 3 with CaaSP can be found in the CaaSP 4.5 documentation.

////
=== Deprecations in 4.2.3
None
////

=== Required Actions

To apply the fix for the CRI-O bug mentioned below, you must perform `skuba-update`.
See https://documentation.suse.com/suse-caasp/4.2/html/caasp-admin/_cluster_updates.html#_base_os_updates for more details.

* {productname} did not detect existing `metrics-server` installed by the administrator via helm, so please remove the installed `metrics-server` manually before running `skuba upgrade addons`.
+
[source,bash]
----
helm delete metrics-server --purge
----

=== Bugs Fixed in 4.2.4 since 4.2.3

* link:https://bugzilla.suse.com/show_bug.cgi?id=1174400[bsc#1174400] [cri-o] $HOME is not used in /etc/passwd when runAsUser is used with crio 1.16.1

[[docs-changes-424]]
=== Documentation Changes

* Added instructions for automatic certificate renewal link:{docurl}/html/caasp-admin/_security.html#_automatic_certificate_renewal[using the `kucero` addon].
* Various minor fixes and improvements, refer to: https://github.com/SUSE/doc-caasp/releases

[[known-issues-424]]
=== Known Issues

* Kubeproxy is not fully deprecated since envoyproxy requires support of Linux Kernel 5.3 and upwards.

==== sles15sp1 aws image is inactive

When deploying on AWS, you need to modify the configuration for {tf} on your management node. You need to set `state = "inactive"` in `/usr/share/caasp/terraform/aws/ami.tf`, to avoid the the error `Error: Invalid index` during deployment of nodes.
