== Changes in 4.1.0

=== {kube} update

{productname} now ships with {kube} {kube_version}.
Most of the significant changes relate to this upgrade, as more than 31 enhancements were merged in the {kube} {kube_version} release.
You can read a short summary of the changes under <<kubernetes_updates>>.
Manual actions are required for 4.1.0 release.

=== Helm security update

Moreover, helm has been updated to fix a security issue (link:https://www.suse.com/security/cve/CVE-2019-18658/[CVE-2019-18658]).

=== Stratos, a web console for {kube}

Stratos is now available as tech preview for {productname}. Stratos is a
web console for {kube} and for Cloud Foundry.
A single instance of Stratos can be used to monitor and interact with different
{kube} clusters as long as their API endpoints are reachable by Stratos.

Stratos integrates with Prometheus: it can scrape metrics collected
by Prometheus and show them using pre-built charts.

Finally Stratos can be used to interact with helm chart repositories. It can
show the charts available and install them straight from its web interface.
It can also show all the workloads that are running on a {kube} that have
been created by helm chart.

[NOTE]
====
The helm chart integration is a tech preview feature of Stratos
that must be enabled at deployment time.
====

=== Required Actions

==== Skuba and helm update Instructions

Update skuba and helm on your management workstation as you would do with any other package.

Refer to: link:https://documentation.suse.com/sles/15-SP1/single-html/SLES-admin/#sec-zypper-softup-update[https://documentation.suse.com/sles/15-SP1/single-html/SLES-admin/#sec-zypper-softup-update]

[WARNING]
====
When running helm-init you may hit a link:https://bugzilla.suse.com/show_bug.cgi?id=1159047[known bug on the certificate validation]:

----
https://kubernetes-charts.storage.googleapis.com is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: x509: certificate signed by unknown authority
----

In order to fix this, run:

----
sudo update-ca-certificates
----

====


After updating helm to latest version on the management host, you have to also upgrade the helm-tiller image in the cluster, by running:

----
helm init \
    --tiller-image registry.suse.com/caasp/v4/helm-tiller:2.16.1 \
    --service-account tiller --upgrade
----

==== Upgrade Your {kube} Cluster

Use skuba to upgrade your {kube} cluster as link:https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#handling_updates[documented in the Administration guide].

[WARNING]
====
Please, do not run `zypper patch` manually on your nodes.
If you do, you will see an error about a conflict when patching {crio}.
This is expected, because the patch is not supposed to be installed this way.

Instead, cluster updates are being handled by skuba as link:{docurl}/single-html/caasp-admin/#handling_updates[documented in the Administration guide].
====

==== Update Your {kube} Manifests for {kube} {kube_version}:

Some API resources are moved to stable, while others have been
moved to different groups or deprecated.

The following will impact your deployment manifests:

*  `DaemonSet`, `Deployment`, `StatefulSet`, and `ReplicaSet` in
  `extensions/` (both `v1beta1` and `v1beta2`) is deprecated.
  Migrate to `apps/v1` group instead for all those objects.
  Please note that `kubectl convert` can help you migrate all the
  necessary fields.
*  `PodSecurityPolicy` in `extensions/v1beta1` is deprecated. Migrate to
  `policy/v1beta1` group for `PodSecurityPolicy`.
  Please note that `kubectl convert` can help you migrate all the
  necessary fields.
*  `NetworkPolicy` in `extensions/v1beta1` is deprecated. Migrate to
  `networking.k8s.io/v1` group for `NetworkPolicy`.
  Please note that `kubectl convert` can help you migrate all the
  necessary fields.
*  `Ingress` in `extensions/v1beta1` is being phased out. Migrate to
  `networking.k8s.io/v1beta1` as soon as possible.
  This new API does not need to update other API fields and therefore
  only a path change is necessary.
*  Custom resource definitions have moved from `apiextensions.k8s.io/v1beta1`
  to `apiextensions.k8s.io/v1`.

Please also see https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ for more details.

=== Bugs Fixed in 4.1.0 since 4.0.3

* link:https://bugzilla.suse.com/show_bug.cgi?id=1144065[bsc#1144065] [cri-o] - (link:https://www.suse.com/security/cve/CVE-2019-10214[CVE-2019-10214]) VUL-0: CVE-2019-10214: libcontainers-common: library does not enforce TLS connections
* link:https://bugzilla.suse.com/show_bug.cgi?id=1118898[bsc#1118898] [cri-o] - (link:https://www.suse.com/security/cve/CVE-2018-16874[CVE-2018-16874]) VUL-0: CVE-2018-16874: go: cmd/go: directory traversal
* link:https://bugzilla.suse.com/show_bug.cgi?id=1100838[bsc#1100838] [cri-o] - cri-o does not block /proc/acpi pathnames (i.e., also affected by (link:https://www.suse.com/security/cve/CVE-2018-10892[CVE-2018-10892]))
* link:https://bugzilla.suse.com/show_bug.cgi?id=1118897[bsc#1118897] [etcd] - (link:https://www.suse.com/security/cve/CVE-2018-16873[CVE-2018-16873]) VUL-0: CVE-2018-16873: go: cmd/go: remote command execution
* link:https://bugzilla.suse.com/show_bug.cgi?id=1118899[bsc#1118899] [etcd] - (link:https://www.suse.com/security/cve/CVE-2018-16875[CVE-2018-16875]) VUL-0: CVE-2018-16875: go: crypto/x509: CPU denial of service
* link:https://bugzilla.suse.com/show_bug.cgi?id=1156646[bsc#1156646] [helm] - (link:https://www.suse.com/security/cve/CVE-2019-18658[CVE-2019-18658]) VUL-0: CVE-2019-18658: helm: commands that deal with loading a chart as a directory or packaging a chart provide an opportunity for a maliciously designed chart to include sensitive content such as /etc/passwd
* link:https://bugzilla.suse.com/show_bug.cgi?id=1152861[bsc#1152861] [kubernetes] - (link:https://www.suse.com/security/cve/CVE-2019-11253[CVE-2019-11253]) VUL-0: CVE-2019-11253: kubernetes: YAML parsing vulnerable to "Billion Laughs" attack, allowing for remote denial of service
* link:https://bugzilla.suse.com/show_bug.cgi?id=1146991[bsc#1146991] [kubernetes] - BPF filesystem is not mounted, possible downtime when cilium pods are restarted
* link:https://bugzilla.suse.com/show_bug.cgi?id=1147142[bsc#1147142] [kubernetes] - Update golang/x/net dependency to bring in fixes for (link:https://www.suse.com/security/cve/CVE-2019-9512[CVE-2019-9512]), (link:https://www.suse.com/security/cve/CVE-2019-9514[CVE-2019-9514])
* link:https://bugzilla.suse.com/show_bug.cgi?id=1143813[bsc#1143813] [kubernetes] - kubelet sometimes starting too fast
* link:https://bugzilla.suse.com/show_bug.cgi?id=1143813[bsc#1143813] [skuba] - CaaSP SSL / PKI / CA Infrastructure unclear and probably inconsistent and wrong?
* link:https://bugzilla.suse.com/show_bug.cgi?id=1152335[bsc#1152335] [supportutils-plugin-suse-caasp] - supportconfig adjustments for CaaSP v4 missing

=== Documentation Updates

* Switched examples to use SUSE supported helm, Prometheus, nginx-ingress and Grafana charts and images
* link:{docurl}caasp-admin/single-html/_security.html#_deployment_with_a_custom_ca_certificate[Added instructions on how to replace {kube} certificates with custom CA certificate]
* link:{docurl}caasp-admin/single-html/_security.html#_replace_server_certificate_signed_by_a_trusted_ca_certificate[Added instructions to configure custom certificates for gangway and dex]
* link:{docurl}caasp-admin/single-html/_software_management.html#_installing_tiller[Added instructions for secured Tiller deployment]
* link:{docurl}caasp-deployment/single-html/#machine-id[Added notes about unique `machine-id` requirement]
* link:{docurl}caasp-deployment/single-html/#_autoyast_preparation[Added timezone configuration example for {ay}]
* link:https://github.com/SUSE/doc-caasp/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc[Various minor bugfixes and improvements]

=== Known issue: skuba upgrade could not parse "Unknown" as version ====

Running "skuba node upgrade plan" might fail with the error "could not parse "Unknown" as version" when a worker, after running "skuba node upgrade apply", had not fully started yet.

If you are running into this issue, please add some delay after running "skuba node upgrade apply" and prior to running "skuba node upgrade plan".

This is tracked in link:https://bugzilla.suse.com/show_bug.cgi?id=1159452[bsc#1159452]
