== What Is New in 5.0.0-beta

=== Base Operating System Is Now {slsa} 15 SP2

{productname} {productmajor} uses standard *{slsa} 15 SP2* as the base platform OS.
{productname} can be installed as an extension on top of that. Because {slsa} 15 is
designed to address both cloud-native and legacy workloads.
these changes make it easier for customers who want to modernize their
infrastructure by moving existing workloads to a {kube} framework.

For information on notable changes when going from {slsa} 15 SP1 to {slsa} 15 SP2, refer to the link:https://www.suse.com/releasenotes/x86_64/SUSE-SLES/15-SP2/#_changes_in_15sp2[{slsa} 15 SP2 Release Notes]

=== Changes to the {kube} Stack

==== Updated Kubernetes

{productname} 5.0.0-beta comes with *{kube} 1.18*. The new {kube} version includes for example notable upgrades to kubectl, storage enhancements, Horizontal Pod Autoscaler (HPI) and advanced scheduling. Some of these features have been available in {productname} for a couple of versions now. For a summary, you can view the link:https://www.suse.com/c/whats-new-in-kubernetes-v1-18-0/[SUSE blog] or see the full version in the link:https://kubernetes.io/docs/setup/release/notes/[official Kubernetes documentation].

// == Updating to {productname} {productmajor}

== Documentation changes



== Known Issues
