== What Is New in 4.5.0

=== Base Operating System Is Now {slsa} 15 SP2

{productname} {productmajor} uses standard *{slsa} 15 SP2* as the base platform OS.
{productname} can be installed as an extension on top of that. Because {slsa} 15 is
designed to address both cloud-native and legacy workloads.
these changes make it easier for customers who want to modernize their
infrastructure by moving existing workloads to a {kube} framework.

==== Changes in the Installation Media

Please pay attention to the change in the installation media of {slsa} 15 SP2. The Unified Installer and Packages DVDs known from SUSE {slsa} 15 SP1 are deprecated and have been replaced by Online Installation Media and Full Installation Media, for further details see link:https://www.suse.com/releasenotes/x86_64/SUSE-SLES/15-SP2/#_changes_in_15sp2[this section] of the *{slsa} 15 SP2 Release Notes*.

For further information on notable changes when going from {slsa} 15 SP1 to {slsa} 15 SP2, also refer to the link:https://www.suse.com/releasenotes/x86_64/SUSE-SLES/15-SP2/[{slsa} 15 SP2 Release Notes].

=== Support disabling routable check in {vmware}

{vmware} {tf} config now supports the option `wait_for_guest_net_routable` to disable {tf} from waiting for a routable network on VM creation. This is useful to prevent an upstream issue in which {tf} hangs waiting for a routable IP even when the VM has one. For more information check the link:https://github.com/hashicorp/terraform-provider-vsphere/issues/1127[bug report]

=== Changes to the {kube} Stack

==== Updated Kubernetes

{productname} 4.5.0 comes with *{kube} 1.18*. The new {kube} version includes for example notable upgrades to kubectl, storage enhancements, Horizontal Pod Autoscaler (HPI) and advanced scheduling. Some of these features have been available in {productname} for a couple of versions now.

You can find a list of changes directly relevant to {productname} here: link:{docurl}single-html/caasp-admin/#k8s-changes-117-118[Changes from {kube} 1.17 to 1.18]

For a more generalized summary, you can view the link:https://www.suse.com/c/whats-new-in-kubernetes-v1-18-0/[SUSE blog] or see the full version in the link:https://kubernetes.io/docs/setup/release/notes/[official Kubernetes documentation].

[#crio-118-config-update]
==== cri-o

This release upgrades `cri-o` to 1.18, which brings support for {kube} 1.18.
This new version, though, requires some manual steps for the upgrade, since the configuration files have been migrated from `sysconfig` to `/etc/crio/crio.conf.d/`.
In order to upgrade, then, you will have to perform the following command before upgrading each node:

----
skuba cluster upgrade localconfig
----

After this you will be able to perform all the `skuba` commands that you would call normally when upgrading {productname}.

=== Kubernetes Audit Log with rsyslog agent

Starting with this version of {productname}, the {kube} audit log will be forwarded to the centralized logging service using `log-agent-rsyslog`.

=== Required Actions

You must update the {crio} configuration files on each node before upgrading, please refer to <<crio-118-config-update>>.

////
==== Helm 3

==== Addon Certificate Rotation

==== GPU-Dependent Workloads

// == Updating to {productname} {productmajor}
////

== Documentation Changes

* Split the airgap deployment guide into a separate document: link:{docurl}single-html/caasp-airgap/[]
* Instructions on how to migrate from Helm 2 to 3, see link:{docurl}single-html/caasp-admin/#helm-2to3-migration[the Administration Guide].
* New chapter on link:{docurl}single-html/caasp-admin/#addon-certificate-rotation[Addon Certificate Rotation in the Administration Guide].
* New chapter on link:{docurl}single-html/caasp-admin/#_gpu_dependent_workloads[GPU-Dependent Workloads in the Administration Guide].
* link:{docurl}single-html/caasp-admin/#_logging[Completely overhauled logging section], reordered Admin guide to incorporate this change.
// * Various other fixes and improvements, refer to: https://github.com/SUSE/doc-caasp/releases/tag/release-5.0.0-beta


== Known Issues

=== In the upgrade process, after the restart of CRI-O and kubelet, some pods might not run properly

This can happen when there are multiple instances of a PodSandbox in a "NotReady" state. As a workaround please make sure to remove any pod in the "NotReady" state using crictl rmp <podid>. Further it is advisable to drain the node that is being upgrade before actually starting the upgrade procedure.

The upstream fix is https://github.com/cri-o/cri-o/pull/4006 which will be included in the next release.

Reference: https://github.com/SUSE/avant-garde/issues/1808


=== etcd: CVE-2020-15106 and CVE-2020-15112

Note the version of etcd shipped with CaaSP 4.5.0 contains two security issues identified as CVE-2020-15106 and CVE-2020-15112

The etcd endpoints should only be accessible inside the cluster if you have set up the firewall rules / network segmentation, following our suggestions in the admin guide; etcd should only be accessible by k8s nodes (or by trusted nodes). Exploiting this vulnerability requires an attacker to take control of the etcd leader in order to send crafted WAL entries, which means access to the SSL certs or local machine access.

Fixes for these will be provided as a maintenance update.


=== envoy: CVE-2020-12605,CVE-2020-8663,CVE-2020-12603 and CVE-2020-12604

Note that the version of envoy shipped with CaaSP 4.5.0 contains security issues idendified as CVE-2020-12605,CVE-2020-8663,CVE-2020-12603 and CVE-2020-12604

These are "Denial of Service" vulnerabilities, and do not expose systems to unauthorized access or data exfiltration. A fix for them will be provided as a maintenance update.

